### ISSUE TITLE
关于云盘的训练数据y2b.tar

### ISSUE THREAD

**Issue by paozhuanyinyuba** [researchmm/TracKit#10]
您好，很棒的工作，但我在下载完您提供的y2b.tar训练数据后，发现train.json里头的bbox标注都是小于等于 1.0的 ， 这是一种中间格式吗  还是说有些问题？

**Comment by JudasDie** [comment]
> 您好，很棒的工作，但我在下载完您提供的y2b.tar训练数据后，发现train.json里头的bbox标注都是小于等于 1.0的 ， 这是一种中间格式吗 还是说有些问题？

Hi, 你好。 因为youtube源数据里面对标注做了归一化。你可以看下源数据的说明。

**Comment by paozhuanyinyuba** [comment]
> > 您好，很棒的工作，但我在下载完您提供的y2b.tar训练数据后，发现train.json里头的bbox标注都是小于等于 1.0的 ， 这是一种中间格式吗 还是说有些问题？
> 
> Hi, 你好。 因为youtube源数据里面对标注做了归一化。你可以看下源数据的说明。

嗯  我看到了，那这个在par_crop.py的时候  是不是要先还原到原尺度，进行par_crop？  如果是这样的话 是不是train.json里面也有是还原到原图像尺度的bbox?

**Comment by JudasDie** [comment]
> > > 您好，很棒的工作，但我在下载完您提供的y2b.tar训练数据后，发现train.json里头的bbox标注都是小于等于 1.0的 ， 这是一种中间格式吗 还是说有些问题？
> > 
> > 
> > Hi, 你好。 因为youtube源数据里面对标注做了归一化。你可以看下源数据的说明。
> 
> 嗯 我看到了，那这个在par_crop.py的时候 是不是要先还原到原尺度，进行par_crop？ 如果是这样的话 是不是train.json里面也有是还原到原图像尺度的bbox?

crop时候需要还原到原本尺度。json不需要，你可以看下dataloader里面怎么处理的，只要有图像原本尺度，在dataloader里面还原就可以。

**Comment by paozhuanyinyuba** [comment]
> > > > 您好，很棒的工作，但我在下载完您提供的y2b.tar训练数据后，发现train.json里头的bbox标注都是小于等于 1.0的 ， 这是一种中间格式吗 还是说有些问题？
> > > 
> > > 
> > > Hi, 你好。 因为youtube源数据里面对标注做了归一化。你可以看下源数据的说明。
> > 
> > 
> > 嗯 我看到了，那这个在par_crop.py的时候 是不是要先还原到原尺度，进行par_crop？ 如果是这样的话 是不是train.json里面也有是还原到原图像尺度的bbox?
> 
> crop时候需要还原到原本尺度。json不需要，你可以看下dataloader里面怎么处理的，只要有图像原本尺度，在dataloader里面还原就可以。

明白了 ， 谢谢解答，祝福！

**Comment by JudasDie** [comment]
> > > > > 您好，很棒的工作，但我在下载完您提供的y2b.tar训练数据后，发现train.json里头的bbox标注都是小于等于 1.0的 ， 这是一种中间格式吗 还是说有些问题？
> > > > 
> > > > 
> > > > Hi, 你好。 因为youtube源数据里面对标注做了归一化。你可以看下源数据的说明。
> > > 
> > > 
> > > 嗯 我看到了，那这个在par_crop.py的时候 是不是要先还原到原尺度，进行par_crop？ 如果是这样的话 是不是train.json里面也有是还原到原图像尺度的bbox?
> > 
> > 
> > crop时候需要还原到原本尺度。json不需要，你可以看下dataloader里面怎么处理的，只要有图像原本尺度，在dataloader里面还原就可以。
> 
> 明白了 ， 谢谢解答，祝福！

不客气，应该的。
