### ISSUE TITLE
Ocean模型的pre-trained model 和 数据对应的json文件链接失效

### ISSUE THREAD

**Issue by ZHXZHX99** [researchmm/TracKit#100]
您好！有关Ocean模型的pre-trained model 和 数据对应的json文件链接失效了，麻烦再次分享一下！谢谢！！

**Comment by JudasDie** [comment]
> 您好！有关Ocean模型的pre-trained model 和 数据对应的json文件链接失效了，麻烦再次分享一下！谢谢！！

Please refer to [here](https://github.com/JudasDie/SOTS).

**Comment by ZHXZHX99** [comment]
非常感谢！
