### ISSUE TITLE
Could u provide the result file of Ocean-offline? (original link is invalid.)

### ISSUE THREAD

**Issue by Soarkey** [researchmm/TracKit#101]
_TracKit_ and _SOTS_ only provide ocean-online results, could u add ocean-offline results?

**Comment by JudasDie** [comment]
> _TracKit_ and _SOTS_ only provide ocean-online results, could u add ocean-offline results?

Hi, SOTS has already provided the results, pls check it.

**Comment by Soarkey** [comment]
got it, thanks!
