### ISSUE TITLE
ocean在Google driver中存储的.pth文件几乎全部失效了

### ISSUE THREAD

**Issue by Sanshi6** [researchmm/TracKit#109]

**Comment by Sanshi6** [comment]
找到了：
https://drive.google.com/drive/folders/1VP9UsBYpqSVbLwXSr6PkHeuUxJjG0QsT

**Comment by Air1000thsummer** [comment]
dear aqua
Are these weight files pre-training weight files for the ocean?

**Comment by Sanshi6** [comment]
> dear aqua Are these weight files pre-training weight files for the ocean?

Yes, the author integrated the Ocean algorithm into another library: https://github.com/JudasDie/SOTS

**Comment by Air1000thsummer** [comment]
thanks！ Aqua sama！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月24日(星期五) 上午10:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [researchmm/TracKit] ocean在Google driver中存储的.pth文件几乎全部失效了 (Issue #109)














  
dear aqua Are these weight files pre-training weight files for the ocean?
  
Yes, the author integrated the Ocean algorithm into another library: https://github.com/JudasDie/SOTS
