### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by RaymondCover** [researchmm/TracKit#11]
Hi, thanks for your work, I have some problem in training.
I find that in TracKit/experiments/train/Ocean.yaml this model train for 50 epoch, but in the paper training for 20 epoch, and the learing rate end_lr also seems for alexnet training.
Another problem is that I only have one 2080ti gpu,  will it influence the results a lot?  Or should I adjust some parameters.
Thanks.

**Comment by JudasDie** [comment]
> Hi, thanks for your work, I have some problem in training.
> I find that in TracKit/experiments/train/Ocean.yaml this model train for 50 epoch, but in the paper training for 20 epoch, and the learing rate end_lr also seems for alexnet training.
> Another problem is that I only have one 2080ti gpu, will it influence the results a lot? Or should I adjust some parameters.
> Thanks.

Hi. 1) The full training is performed for 50 epochs, as detailed in `Sec.5.1` in the paper. The `Sec.5.3` provides the abolition for training 20 epochs. When conducting your idea on this framework, you could first train 20 epoch for fast evaluation. After getting a good result, then do the full train.  2) One GPU may decrease the performance since the batch size is much smaller than 256. You could try to increase the batch size.

**Comment by paozhuanyinyuba** [comment]
hello, 在数据集一样，用代码中提供的设置文件，用八卡训练的效果。并不能达到论文中的效果，可能是什么原因呢？ 相差还比较大

**Comment by JudasDie** [comment]
> hello, 在数据集一样，用代码中提供的设置文件，用八卡训练的效果。并不能达到论文中的效果，可能是什么原因呢？ 相差还比较大

Hi, 请问所有配置都一样么？可以展示下你的log么？另外你epoch test后结果是多少(VOT19)？以及调参后结果是多少？

**Comment by paozhuanyinyuba** [comment]
> > hello, 在数据集一样，用代码中提供的设置文件，用八卡训练的效果。并不能达到论文中的效果，可能是什么原因呢？ 相差还比较大
> 
> Hi, 请问所有配置都一样么？可以展示下你的log么？另外你epoch test后结果是多少(VOT19)？以及调参后结果是多少？

配置就用的 experiments/train/Ocean.yaml,  在VOT2018上的结果是 EAO 0.357

**Comment by JudasDie** [comment]
> > > hello, 在数据集一样，用代码中提供的设置文件，用八卡训练的效果。并不能达到论文中的效果，可能是什么原因呢？ 相差还比较大
> > 
> > 
> > Hi, 请问所有配置都一样么？可以展示下你的log么？另外你epoch test后结果是多少(VOT19)？以及调参后结果是多少？
> 
> 配置就用的 experiments/train/Ocean.yaml, 在VOT2018上的结果是 EAO 0.357

1）如果方便的话麻烦传给我一份train/epoch test/tune的log，我帮忙check下，如果github不能传的话请发我邮箱zhangzhipeng2017@ia.ac.cn  2) 请问可以同时反馈一下VOT19的结果么？

**Comment by paozhuanyinyuba** [comment]
> > > > hello, 在数据集一样，用代码中提供的设置文件，用八卡训练的效果。并不能达到论文中的效果，可能是什么原因呢？ 相差还比较大
> > > 
> > > 
> > > Hi, 请问所有配置都一样么？可以展示下你的log么？另外你epoch test后结果是多少(VOT19)？以及调参后结果是多少？
> > 
> > 
> > 配置就用的 experiments/train/Ocean.yaml, 在VOT2018上的结果是 EAO 0.357
> 
> 1）如果方便的话麻烦传给我一份train/epoch test/tune的log，我帮忙check下，如果github不能传的话请发我邮箱[zhangzhipeng2017@ia.ac.cn](mailto:zhangzhipeng2017@ia.ac.cn) 2) 请问可以同时反馈一下VOT19的结果么？

行  我找时间整理下，  我觉着问题是不是出现在 bn上， 我粗略看了下好像没有用synbn

**Comment by JudasDie** [comment]
> > > > > hello, 在数据集一样，用代码中提供的设置文件，用八卡训练的效果。并不能达到论文中的效果，可能是什么原因呢？ 相差还比较大
> > > > 
> > > > 
> > > > Hi, 请问所有配置都一样么？可以展示下你的log么？另外你epoch test后结果是多少(VOT19)？以及调参后结果是多少？
> > > 
> > > 
> > > 配置就用的 experiments/train/Ocean.yaml, 在VOT2018上的结果是 EAO 0.357
> > 
> > 
> > 1）如果方便的话麻烦传给我一份train/epoch test/tune的log，我帮忙check下，如果github不能传的话请发我邮箱[zhangzhipeng2017@ia.ac.cn](mailto:zhangzhipeng2017@ia.ac.cn) 2) 请问可以同时反馈一下VOT19的结果么？
> 
> 行 我找时间整理下， 我觉着问题是不是出现在 bn上， 我粗略看了下好像没有用synbn; EAO 0.357是没有 tune para的结果

应该不是，我之前复现波动没有这么大，也麻烦你顺便测下19，因为18比较容易过拟合，19和20相对稳定，用来测试可能更容易反映tracker性能(个人经验仅供参考)。也麻烦你整理完邮箱发我下，我也找时间帮你check。
