### ISSUE TITLE
UAV123.json pls

### ISSUE THREAD

**Issue by kasuo511** [researchmm/TracKit#12]
Thanks for sharing!
Wanting to test UAV123 dataset, could you pls provide the UAV.json file? 
Or just the toolkit that can generate the json file from txt files. Thanks advanced!

**Comment by JudasDie** [comment]
> Thanks for sharing!
> Wanting to test UAV123 dataset, could you pls provide the UAV.json file?
> Or just the toolkit that can generate the json file from txt files. Thanks advanced!

Hi. I haven't tested the model on UAV123. You could check the VOT or OTB JSON format to generate UAV for now. I will provide one later.

**Comment by kasuo511** [comment]
> > Thanks for sharing!
> > Wanting to test UAV123 dataset, could you pls provide the UAV.json file?
> > Or just the toolkit that can generate the json file from txt files. Thanks advanced!
> 
> Hi. I haven't tested the model on UAV123. You could check the VOT or OTB JSON format to generate UAV for now. I will provide one later.

Thanks, I'll try to generate UAV123.json

**Comment by kasuo511** [comment]
[UAV123.zip](https://github.com/researchmm/TracKit/files/4946523/UAV123.zip)


> > Thanks for sharing!
> > Wanting to test UAV123 dataset, could you pls provide the UAV.json file?
> > Or just the toolkit that can generate the json file from txt files. Thanks advanced!
> 
> Hi. I haven't tested the model on UAV123. You could check the VOT or OTB JSON format to generate UAV for now. I will provide one later.

Have generated a UAV123 json file, attached here if it helps

**Comment by JudasDie** [comment]
> [UAV123.zip](https://github.com/researchmm/TracKit/files/4946523/UAV123.zip)
> 
> > > Thanks for sharing!
> > > Wanting to test UAV123 dataset, could you pls provide the UAV.json file?
> > > Or just the toolkit that can generate the json file from txt files. Thanks advanced!
> > 
> > 
> > Hi. I haven't tested the model on UAV123. You could check the VOT or OTB JSON format to generate UAV for now. I will provide one later.
> 
> Have generated a UAV123 json file, attached here if it helps

Thanks! Could I upload it to the GDrive to share it with other readers?

**Comment by kasuo511** [comment]
> > [UAV123.zip](https://github.com/researchmm/TracKit/files/4946523/UAV123.zip)
> > > > Thanks for sharing!
> > > > Wanting to test UAV123 dataset, could you pls provide the UAV.json file?
> > > > Or just the toolkit that can generate the json file from txt files. Thanks advanced!
> > > 
> > > 
> > > Hi. I haven't tested the model on UAV123. You could check the VOT or OTB JSON format to generate UAV for now. I will provide one later.
> > 
> > 
> > Have generated a UAV123 json file, attached here if it helps
> 
> Thanks! Could I upload it to the GDrive to share it with other readers?

It's totally OK to share.
