### ISSUE TITLE
download quota exceeded for this file so you can not download it at this time 

### ISSUE THREAD

**Issue by cjfcsjt** [researchmm/TracKit#14]
Hi,
When I try to download the pre-trained PyTorch model from google drive, it told me 'download quota exceeded for this file so you can not download it at this time ', are there any other resources I can download?

**Comment by JudasDie** [comment]
> Hi,
> When I try to download the pre-trained PyTorch model from google drive, it told me 'download quota exceeded for this file so you can not download it at this time ', are there any other resources I can download?

Hi, I tried just now and it can be successfully downloaded. Is there anything wrong with your VPN?
