### ISSUE TITLE
How to train online branch

### ISSUE THREAD

**Issue by RaymondCover** [researchmm/TracKit#15]
我发现论文中的在线更新模块需要train一个与resnet相同的block，以及DiMP需要的初始化参数。但我在代码中没能找到如何训练该分支的方法，能否告知我如何训练该分支，
这个分支是和离线的孪生网络共同训练的吗？还是先训练离线网络，再训练在线网络？
谢谢。

**Comment by JudasDie** [comment]
> 我发现论文中的在线更新模块需要train一个与resnet相同的block，以及DiMP需要的初始化参数。但我在代码中没能找到如何训练该分支的方法，能否告知我如何训练该分支，
> 这个分支是和离线的孪生网络共同训练的吗？还是先训练离线网络，再训练在线网络？
> 谢谢。

先离线再在线。不过我比较建议你先试试直接把siamese和原本的dimp/atom的结果直接融合下，大概有个心理结果融合后结果在哪个范围。融合系数比较敏感，建议仔细调调。

**Comment by JianTao-zjut** [comment]
> > 我发现论文中的在线更新模块需要train一个与resnet相同的block，以及DiMP需要的初始化参数。但我在代码中没能找到如何训练该分支的方法，能否告知我如何训练该分支，
> > 这个分支是和离线的孪生网络共同训练的吗？还是先训练离线网络，再训练在线网络？
> > 谢谢。
> 
> 先离线再在线。不过我比较建议你先试试直接把siamese和原本的dimp/atom的结果直接融合下，大概有个心理结果融合后结果在哪个范围。融合系数比较敏感，建议仔细调调。

请问可以放出在线训练的代码吗，看过很多使用在线分支的算法都没有详细描述过训练方法。。。我想复现都无从下手

**Comment by JudasDie** [comment]
> > > 我发现论文中的在线更新模块需要train一个与resnet相同的block，以及DiMP需要的初始化参数。但我在代码中没能找到如何训练该分支的方法，能否告知我如何训练该分支，
> > > 这个分支是和离线的孪生网络共同训练的吗？还是先训练离线网络，再训练在线网络？
> > > 谢谢。
> > 
> > 
> > 先离线再在线。不过我比较建议你先试试直接把siamese和原本的dimp/atom的结果直接融合下，大概有个心理结果融合后结果在哪个范围。融合系数比较敏感，建议仔细调调。
> 
> 请问可以放出在线训练的代码吗，看过很多使用在线分支的算法都没有详细描述过训练方法。。。我想复现都无从下手

暂时没时间整理，online那部分训练比较麻烦，建议对比offline。
