### ISSUE TITLE
multiple objects

### ISSUE THREAD

**Issue by eastplainzhang** [researchmm/TracKit#16]
首先感谢您的工作，请问这个可以完成多目标的任务吗，对多目标进行分割和跟踪

**Comment by JudasDie** [comment]
> 首先感谢您的工作，请问这个可以完成多目标的任务吗，对多目标进行分割和跟踪

你好。可以对每个目标单独追踪，比如DAVIS17这种数据。对于MOT数据集这种有目标消失的以及要预测ID的，建议结合MOT算法一起，比如将其作为一个短期追踪器用在MOT算法里面。
