### ISSUE TITLE
The difference between eval and test

### ISSUE THREAD

**Issue by zhjw0927** [researchmm/TracKit#18]
I want to know diff between eval and test.
If I run a demo, is there existing code? Or which file I should change?
Thank you!

**Comment by JudasDie** [comment]
> I want to know diff between eval and test.
> If I run a demo, is there existing code? Or which file I should change?
> Thank you!

Hi, could you pls give a clearer description about your question? I'm a little confused.

**Comment by zhjw0927** [comment]
![image](https://user-images.githubusercontent.com/42128459/90851113-52b6a800-e3a6-11ea-9644-561b42ad87bd.png)

I want to know what is the function of test， and function of eval?
Thank you!

**Comment by JudasDie** [comment]
> ![image](https://user-images.githubusercontent.com/42128459/90851113-52b6a800-e3a6-11ea-9644-561b42ad87bd.png)
> 
> I want to know what is the function of test， and function of eval?
> Thank you!

`Testing` indicates that you run the model on a benchmark, generating the `.txt` results. `Evaluation` denotes that you get the detailed performance, e.g. AUC/EAO, based on the generated `.txt`  results. I would suggest you carefully read all codes first to know the complete pipeline of tracking.

**Comment by zhjw0927** [comment]
Yeah, I got it.
I'm really new to tracking. Thank you for advice!

**Comment by JudasDie** [comment]
> Yeah, I got it.
> I'm really new to tracking. Thank you for advice!

You are welcome. Glad to help you.
