### ISSUE TITLE
why tracking/test_ocean.py can import lib/tracker/ocean.py?

### ISSUE THREAD

**Issue by zhjw0927** [researchmm/TracKit#19]
In tracking/test_ocean.py, have such a code: from tracker.ocean import Ocean
tracker in lib, while lib and tracking are sibling directories.
why can import it?
Thank you!

**Comment by JudasDie** [comment]
> In tracking/test_ocean.py, have such a code: from tracker.ocean import Ocean
> tracker in lib, while lib and tracking are sibling directories.
> why can import it?
> Thank you!

Hi, please refer to `_init_path.py`.
