### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by zhu2014yi** [researchmm/TracKit#2]
请问你们这个网络要训练多久？

**Comment by JudasDie** [comment]
> 请问你们这个网络要训练多久？

Hi, it takes about 24 or slightly more hours.

**Comment by zhu2014yi** [comment]
thanks

**Comment by penghouwen** [comment]
> > 请问你们这个网络要训练多久？
> 
> Hi, it takes about 24 or slightly more hours on 8 V100.

@JudasDie  Since the training of 8 V100 GPUs  is a high computation demand for some researchers, is it possible to provide versions with low computation cost? If possible, it will be helpful for many peers who are interested in this work.
