### ISSUE TITLE
About hyperparameters for SiamDW

### ISSUE THREAD

**Issue by zhengjilai** [researchmm/TracKit#20]
Hi. Recently I'm experimenting SiamDW on TracKit, but could not obtain the wanted EAO as 0.280 on VOT2018. 
So I open this issue for some help. Some important configurations are listed as follows.

My CUDA version is 10.2 (NVIDIA driver 440.36), and the conda env is constructed directly with your provided script in TracKit framework.

The pretrained model is collected from https://drive.google.com/file/d/1sfmy1nImNw_mstGLEOgpmJydQvSuaobI/view, 
with its md5sum as 5415686007b313685065cf8f3b916742. 

The hyper-parameters we utilize are collected from https://github.com/researchmm/SiamDW.
```
VOT2018:
    scale_step: 1.0085
    scale_lr: 0.2294
    scale_penalty: 0.9686
    w_influence: 0.1817
```

The raw tracking result we obtain on VOT2018 with pysot-toolkit is listed as follows, 0.013 less than the reported 0.280.
```
-----------------------------------------------------------------------------
|Tracker Name| Accuracy | Robustness | Lost Number |  EAO  |
-----------------------------------------------------------------------------
|   SiamDW   |  0.504   |    0.440   |    94.0     | 0.267 |
-----------------------------------------------------------------------------
```
I really appreciate your great work in this repo but I'd like to figure out which mistake I have made above. 
Thanks in advance.

**Comment by JudasDie** [comment]
> Hi. Recently I'm experimenting SiamDW on TracKit, but could not obtain the wanted EAO as 0.280 on VOT2018.
> So I open this issue for some help. Some important configurations are listed as follows.
> 
> My CUDA version is 10.2 (NVIDIA driver 440.36), and the conda env is constructed directly with your provided script in TracKit framework.
> 
> The pretrained model is collected from https://drive.google.com/file/d/1sfmy1nImNw_mstGLEOgpmJydQvSuaobI/view,
> with its md5sum as 5415686007b313685065cf8f3b916742.
> 
> The hyper-parameters we utilize are collected from https://github.com/researchmm/SiamDW.
> 
> ```
> VOT2018:
>     scale_step: 1.0085
>     scale_lr: 0.2294
>     scale_penalty: 0.9686
>     w_influence: 0.1817
> ```
> 
> The raw tracking result we obtain on VOT2018 with pysot-toolkit is listed as follows, 0.013 less than the reported 0.280.
> 
> ```
> -----------------------------------------------------------------------------
> |Tracker Name| Accuracy | Robustness | Lost Number |  EAO  |
> -----------------------------------------------------------------------------
> |   SiamDW   |  0.504   |    0.440   |    94.0     | 0.267 |
> -----------------------------------------------------------------------------
> ```
> 
> I really appreciate your great work in this repo but I'd like to figure out which mistake I have made above.
> Thanks in advance.

Checking and Fixing.

**Comment by JudasDie** [comment]
> > Hi. Recently I'm experimenting SiamDW on TracKit, but could not obtain the wanted EAO as 0.280 on VOT2018.
> > So I open this issue for some help. Some important configurations are listed as follows.
> > My CUDA version is 10.2 (NVIDIA driver 440.36), and the conda env is constructed directly with your provided script in TracKit framework.
> > The pretrained model is collected from https://drive.google.com/file/d/1sfmy1nImNw_mstGLEOgpmJydQvSuaobI/view,
> > with its md5sum as 5415686007b313685065cf8f3b916742.
> > The hyper-parameters we utilize are collected from https://github.com/researchmm/SiamDW.
> > ```
> > VOT2018:
> >     scale_step: 1.0085
> >     scale_lr: 0.2294
> >     scale_penalty: 0.9686
> >     w_influence: 0.1817
> > ```
> > 
> > 
> > The raw tracking result we obtain on VOT2018 with pysot-toolkit is listed as follows, 0.013 less than the reported 0.280.
> > ```
> > -----------------------------------------------------------------------------
> > |Tracker Name| Accuracy | Robustness | Lost Number |  EAO  |
> > -----------------------------------------------------------------------------
> > |   SiamDW   |  0.504   |    0.440   |    94.0     | 0.267 |
> > -----------------------------------------------------------------------------
> > ```
> > 
> > 
> > I really appreciate your great work in this repo but I'd like to figure out which mistake I have made above.
> > Thanks in advance.
> 
> Checking and Fixing.

Pls check the new hyper.
