### ISSUE TITLE
about ocean plus code and paper?

### ISSUE THREAD

**Issue by zlj199502** [researchmm/TracKit#23]
Hi,
Thanks for your excellent work.
When will you release the ocean plus code and paper?

Best

**Comment by JudasDie** [comment]
> Hi,
> Thanks for your excellent work.
> When will you release the ocean plus code and paper?
> 
> Best

Hi, we may update the paper and code at about 9.15 (before).
Thanks.

**Comment by zlj199502** [comment]
Thanks!
I'll look forward to your update.
BTW, your paper is submitted to ECCVW?

**Comment by JudasDie** [comment]
> Thanks!
> I'll look forward to your update.
> BTW, your paper is submitted to ECCVW?

No, we plan to submit to other conference.

**Comment by JudasDie** [comment]
> Thanks!
> I'll look forward to your update.
> BTW, your paper is submitted to ECCVW?

Code has been released. Hope this can help you.
