### ISSUE TITLE
tune problem

### ISSUE THREAD

**Issue by zzzmm1** [researchmm/TracKit#24]
Hi, thanks for your work.
I got the "DeprecationWarning: The redirect_output argument is deprecated." when I tune the training models.
It seems that the latest version of ray is not suitable.
Could you show us  which version of ray do you use?
And is there any more requirements for tuning?

**Comment by JudasDie** [comment]
> Hi, thanks for your work.
> I got the "DeprecationWarning: The redirect_output argument is deprecated." when I tune the training models.
> It seems that the latest version of ray is not suitable.
> Could you show us which version of ray do you use?
> And is there any more requirements for tuning?

Hi, could you pls try ray==0.6.0?

**Comment by zzzmm1** [comment]
ray==0.6.0 works. 
Thanks!
