### ISSUE TITLE
NameError: name 'TRTModule' is not defined

### ISSUE THREAD

**Issue by tian961214** [researchmm/TracKit#26]
请问这个问题怎么解决，我没有看到torch2trt文件呀

**Comment by JudasDie** [comment]
> 请问这个问题怎么解决，我没有看到torch2trt文件呀

你好，麻烦检查是否是你的tensort是否正确安装。 torch2rt和tensort都可以自测是否安装成功。

**Comment by tian961214** [comment]
谢谢啦！已经解决了，但是又遇到一个新的问题，就是在eval阶段，VOT2018.json文件中怎么有color这个路径呀，下载的VOT2018中并没有这个路径呀

**Comment by JudasDie** [comment]
> 谢谢啦！已经解决了，但是又遇到一个新的问题，就是在eval阶段，VOT2018.json文件中怎么有color这个路径呀，下载的VOT2018中并没有这个路径呀

VOT有的年份有color有的没有，如果没记错的话我自己是统一处理了。如果没的话你可以在读图路径那个字符串去掉'color'就可以了，或者你把VOT数据简单处理下，移到color文件夹，几行代码就可以了。

**Comment by tian961214** [comment]
不好意思，我又遇到一个新的问题，就是在验证OTB的结果时，OTB2015.json文件中并没有video这个键值
![image](https://user-images.githubusercontent.com/58418041/92078025-24968680-edf0-11ea-8d49-abc6569f5d42.png)
