### ISSUE TITLE
About training time.

### ISSUE THREAD

**Issue by zorrocai** [researchmm/TracKit#27]
Hi, thanks for your excellent work. I notice that Ocean trained with Youtube-BB, VID, DET, GOT-10K and COCO on 8 Tesla V100 GPUs. Not everyone could afford the perfect hardware resources and huge datasets. I wonder how long  time does it take on training?

**Comment by JudasDie** [comment]
> Hi, thanks for your excellent work. I notice that Ocean trained with Youtube-BB, VID, DET, GOT-10K and COCO on 8 Tesla V100 GPUs. Not everyone could afford the perfect hardware resources and huge datasets. I wonder how long time does it take on training?

Hi, 8 GPUs are enough for training. It takes about 1 day to train.  If you want to accelerate your experiments, you could modify the code to DDP or use dali to accelerate the training.

**Comment by zorrocai** [comment]
Thanks for the quick response~
