### ISSUE TITLE
在下载完youtube后，全是y2b.tar.000这样的文件，还需要怎么进一步处理呀

### ISSUE THREAD

**Issue by tian961214** [researchmm/TracKit#28]
问的问题比较幼稚，但是实在是对您的工作很感兴趣

**Comment by JudasDie** [comment]
> 问的问题比较幼稚，但是实在是对您的工作很感兴趣

你好，麻烦参照`lib/dataset/crop`里面的脚本，有说明。YTB你下载下来多少大小？我记我们当时10T左右？
