### ISSUE TITLE
Data Downloading Problem

### ISSUE THREAD

**Issue by MasterBin-IIAU** [researchmm/TracKit#3]
Hi, since the size of training data is large (y2b is up to 130+GB), it is quite hard to directly download in the browser. I also try to use command-line method. (https://www.toodyao.com/?p=3846) But I can't obtain FILEID. (when I click y2b, the returned google drive link is shown as below, https://drive.google.com/file/d/1XntleNeFDKNS9kdspn9xY7UWuV2USCmt/view?usp=sharing. I can't find FILEID). 
So can you help me? or are there alternative methods to download these data? Thank you

**Comment by JudasDie** [comment]
> Hi, since the size of training data is large (y2b is up to 130+GB), it is quite hard to directly download in the browser. I also try to use command-line method. (https://www.toodyao.com/?p=3846) But I can't obtain FILEID. (when I click y2b, the returned google drive link is shown as below, https://drive.google.com/file/d/1XntleNeFDKNS9kdspn9xY7UWuV2USCmt/view?usp=sharing. I can't find FILEID).
> So can you help me? or are there alternative methods to download these data? Thank you

Hi, Thanks for your interest. The alternative method is to download the original YTB dataset and process it by yourself. The original YTB (video format) is about 10TB.

**Comment by penghouwen** [comment]
@JudasDie  Zhipeng, another alternative is to divide the training data into several small files, such that other researchers are able to download the data easily when the internet is not stable.

**Comment by MasterBin-IIAU** [comment]
As shown in https://drive.google.com/drive/folders/1ehjVhg6ewdWSWt709zd1TkjWF7UJlQlq , 
the datasets have been split into subfiles no larger than 5GB. Now the download is easy. Thank you
