### ISSUE TITLE
online PrRoIPooling

### ISSUE THREAD

**Issue by zhjw0927** [researchmm/TracKit#31]
PermissionError: [Errno 13] Permission denied: '/tmp/torch_extensions/_prroi_pooling'
在使用online时，报上述错误，因为PrRoIPooling是用c写的，我没有找到如何更改路径到用户目录下。
您有解决方法吗？
还有，我在阅读该源码时，绕来绕去的，非常乱，您有什么好的建议吗？更进一步，您在写出这么优秀的项目，经过了哪些学习呢？有推荐的课程/书籍/方法吗？
谢谢！

**Comment by JudasDie** [comment]
> PermissionError: [Errno 13] Permission denied: '/tmp/torch_extensions/_prroi_pooling'
> 在使用online时，报上述错误，因为PrRoIPooling是用c写的，我没有找到如何更改路径到用户目录下。
> 您有解决方法吗？
> 还有，我在阅读该源码时，绕来绕去的，非常乱，您有什么好的建议吗？更进一步，您在写出这么优秀的项目，经过了哪些学习呢？有推荐的课程/书籍/方法吗？
> 谢谢！

1.  RTX2080Ti/V100+CUDA10或者1080Ti+CUDA9配置现在版本应该不会有错，你可以检查下cuda版本之类。如果还没解决，可以在PrROI的repo下问下他们是否有和你环境一致的版本。

2. 你那个看起来是没权限`sudo chmod -R 0777 /tmp/`就可以了，建议先熟悉下linux基本操作哈。

3.  online源码参照ATOM/DIMP，实际不是他们绕，而是封装的比较高，比价工程，多debug熟悉就好了。我也还在学习中，还不敢说优秀，多debug，多参考好的代码整理就好了。

**Comment by zhjw0927** [comment]
> > PermissionError: [Errno 13] Permission denied: '/tmp/torch_extensions/_prroi_pooling'
> > 在使用online时，报上述错误，因为PrRoIPooling是用c写的，我没有找到如何更改路径到用户目录下。
> > 您有解决方法吗？
> > 还有，我在阅读该源码时，绕来绕去的，非常乱，您有什么好的建议吗？更进一步，您在写出这么优秀的项目，经过了哪些学习呢？有推荐的课程/书籍/方法吗？
> > 谢谢！
> 
> 1. RTX2080Ti/V100+CUDA10或者1080Ti+CUDA9配置现在版本应该不会有错，你可以检查下cuda版本之类。如果还没解决，可以在PrROI的repo下问下他们是否有和你环境一致的版本。
> 2. 你那个看起来是没权限`sudo chmod -R 0777 /tmp/`就可以了，建议先熟悉下linux基本操作哈。
> 3. online源码参照ATOM/DIMP，实际不是他们绕，而是封装的比较高，比价工程，多debug熟悉就好了。我也还在学习中，还不敢说优秀，多debug，多参考好的代码整理就好了。

感谢您的回复！
permissionError问题，是因为将temp文件写在了/tmp中，会上锁，导致其他用户不能再写入，这是pytorch的bug，于>=1.6版本修复了。
目前，我在学习设计模式，希望对阅读源码有帮助。
