### ISSUE TITLE
online steepest descent distancemap

### ISSUE THREAD

**Issue by zhjw0927** [researchmm/TracKit#32]
我对最速下降中的 distancemap不是很理解，原理和计算步骤不太懂。
请问，它的物理意义是什么？在代码中它输出torch.size([30,100,14,14])的tensor，
30维度表示图像数量，后面三个维度就不懂了。
希望您解答下，谢谢！

**Comment by JudasDie** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    建议知识性讨论可以邮件讨论，github主要还是大家交流下code。另online部分知识性问题可以细读下ATOM和DIMP以及网上相关的讲解。
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    


    --From: Zhang Zhipeng Institution: National Laboratory of Pattern Recognition Address: 95 Zhongguancun East Road, 100190, BEIJING, CHINA Email: zhangzhipeng2017@ia.ac.cn  Best Wishes

        
    
     

    On 9/25/2020 11:13，zhjw0927<notifications@github.com> wrote： 



我对最速下降中的 distancemap不是很理解，原理和计算步骤不太懂。
请问，它的物理意义是什么？在代码中它输出torch.size([30,100,14,14])的tensor，
30维度表示图像数量，后面三个维度就不懂了。
希望您解答下，谢谢！
