### ISSUE TITLE
A problem about testing lasot

### ISSUE THREAD

**Issue by twotwo2** [researchmm/TracKit#33]
Thank you for your excellent work. I have a problem about testing on LaSOT. On the paper of _LaSOT: A High-quality Benchmark for Large-scale Single Object Tracking_, it has proposed two evaluation protocols. Do you follow the second evalution protocol: train the tracker only using LaSOT training subset and test on the testing subset?

**Comment by JudasDie** [comment]
> Thank you for your excellent work. I have a problem about testing on LaSOT. On the paper of _LaSOT: A High-quality Benchmark for Large-scale Single Object Tracking_, it has proposed two evaluation protocols. Do you follow the second evalution protocol: train the tracker only using LaSOT training subset and test on the testing subset?

Pls refer to the paper. I would suggest you keep consistent with the "compared methods".
