### ISSUE TITLE
no object-aware model

### ISSUE THREAD

**Issue by zzzmm1** [researchmm/TracKit#34]
I am doing some work base on the no object-aware verison.
I wonder what‘s the results of OceanNoOA.pth in VOT2018 and VOT2019?
What I get from the paper is that the EAO should be 0.438 in VOT2018. But in my test, it is much lower.
And I didn't find the VOT2019 results in the paper for OceanNoOA.pth.
Thanks for your help!

**Comment by JudasDie** [comment]
> I am doing some work base on the no object-aware verison.
> I wonder what‘s the results of OceanNoOA.pth in VOT2018 and VOT2019?
> What I get from the paper is that the EAO should be 0.438 in VOT2018. But in my test, it is much lower.
> And I didn't find the VOT2019 results in the paper for OceanNoOA.pth.
> Thanks for your help!

The default hyper-params in yaml files are made for OA model. If you want to test NoOA model, please use online parameters (except for the fusion ratio). VOT2019 is 0.32 (also use the online hypers to test no OA model).

**Comment by zzzmm1** [comment]
Thanks! I will try.

**Comment by zzzmm1** [comment]
I test NoOA model using online parameters.
And I got |   Ocean    |  0.581   |   0.169    |    36.0     | 0.437 | in VOT2018 and |   Ocean    |  0.573   |   0.346    |    69.0     | 0.308 |  in VOT2019. 
There is still some gap between EAO 0.320 and 0.308 in VOT2019, any suggestions?

**Comment by JudasDie** [comment]
> I test NoOA model using online parameters.
> And I got | Ocean | 0.581 | 0.169 | 36.0 | 0.437 | in VOT2018 and | Ocean | 0.573 | 0.346 | 69.0 | 0.308 | in VOT2019.
> There is still some gap between EAO 0.320 and 0.308 in VOT2019, any suggestions?

Could you detail the hyper used for 19 testing?

**Comment by zzzmm1** [comment]
hyper-parameters: penalty_k: 0.06, wi: 0.484, lr: 0.644, ratio: 0.94, small_sz: 255, big_sz: 287

**Comment by JudasDie** [comment]
> hyper-parameters: penalty_k: 0.06, wi: 0.484, lr: 0.644, ratio: 0.94, small_sz: 255, big_sz: 287

Pls check two things: 1) not use align (ratio hyper is useless)  2) print hypers in `lib/tracker/ocean.py` to do double-check. I just ask one guy who recently test VOT19-noOA, and she gets EAO of 0.323. It should not be a problem here.

**Comment by zzzmm1** [comment]
Thanks! I will check.

**Comment by zzzmm1** [comment]
I have checked that I didn't use align.  (The ratio hyper is not used.) 
I test several times, the result is same 0.308.
And the double-check result is ======= hyper-parameters: penalty_k: 0.06, wi: 0.484, lr: 0.644, ratio: 0.93, instance_sz: 287, score_sz: 29 =======
I also test OceanV.pth in VOT2019 with offline hyper and get EAO 0.323.
Is the performance gap between NoOA and OA model is small in VOT2019, if 0.32(or 0.323) vs 0.327? But in VOT2018, it is 0.467 vs 0.438.
Another question, I  test OceanV.pth in VOT2019 with offline hyper but only get EAO 0.437.
I download ocean_raw_results and get the same results in paper, it seems that my testing_dataset is work.

**Comment by JudasDie** [comment]
> I have checked that I didn't use align. (The ratio hyper is not used.)
> I test several times, the result is same 0.308.
> And the double-check result is ======= hyper-parameters: penalty_k: 0.06, wi: 0.484, lr: 0.644, ratio: 0.93, instance_sz: 287, score_sz: 29 =======
> I also test OceanV.pth in VOT2019 with offline hyper and get EAO 0.323.
> Is the performance gap between NoOA and OA model is small in VOT2019, if 0.32(or 0.323) vs 0.327? But in VOT2018, it is 0.467 vs 0.438.
> Another question, I test OceanV.pth in VOT2019 with offline hyper but only get EAO 0.437.
> I download ocean_raw_results and get the same results in paper, it seems that my testing_dataset is work.

1. Under TracKit env, OA on VOT2019 is 0.33 (a little higher than that of paper), No OA is 0.323, exceeds almost 1 point. And VOT2018 is much more sensitive to model and hypers, you may not use it as validation. 
2. I would offer you an email about the aforementioned guy (594387862@qq.com), and you may discuss it with her since she tests NOOA very recently. If you cannot solve it, pls let me know.
3. Besides, pls use TracKit env to test models. 
4. I'm a little confused about the question "Another question, I test OceanV.pth in VOT2019 with offline hyper but only get EAO 0.437". If you mean VOT18, I think you may remove `results/VOT2018` first before you test another model on VOT18.

**Comment by zzzmm1** [comment]
Problem solved! Thanks!

**Comment by JudasDie** [comment]
> Problem solved! Thanks!

You are welcome. Glad to hear that.
