### ISSUE TITLE
evaluation on got-10k

### ISSUE THREAD

**Issue by UmarSpa** [researchmm/TracKit#38]
Hi,

I can see that you have provided the json files needed to do evaluation on VOT2019. But there are no such files for got-10k dataset. Can you please provide those as well ?

Thanks

**Comment by UmarSpa** [comment]
And also in experiments/test/ there is no GOT10K directory. In fact when I try to do testing, I get the following Exception:

Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '/TracKit-master/lib/tracker/../../experiments/test/GOT10K/Ocean.yaml'

any help here would be very appreciated.

@JudasDie @

**Comment by JudasDie** [comment]
> And also in experiments/test/ there is no GOT10K directory. In fact when I try to do testing, I get the following Exception:
> 
> Exception has occurred: FileNotFoundError
> [Errno 2] No such file or directory: '/TracKit-master/lib/tracker/../../experiments/test/GOT10K/Ocean.yaml'
> 
> any help here would be very appreciated.
> 
> @JudasDie

Hi, checking and fixing.

**Comment by zzzmm1** [comment]
Could you please provide the  evaluation and tpe tuning code for GOT10KVAL?
And Is GOT10K sensitive to hyperparameters?
Thanks for your help!

**Comment by JudasDie** [comment]
> > And also in experiments/test/ there is no GOT10K directory. In fact when I try to do testing, I get the following Exception:
> > Exception has occurred: FileNotFoundError
> > [Errno 2] No such file or directory: '/TracKit-master/lib/tracker/../../experiments/test/GOT10K/Ocean.yaml'
> > any help here would be very appreciated.
> > @JudasDie
> 
> Hi, checking and fixing.

Updated, pls download the corresponding model from GoogleDrive (see ocean.md)
