### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by zhu2014yi** [researchmm/TracKit#4]
请问之前pysot下载的那些det、ytb、coco、vid能否直接拿来用，我看他们也是crop511的

**Comment by JudasDie** [comment]
> 请问之前pysot下载的那些det、ytb、coco、vid能否直接拿来用，我看他们也是crop511的

你好，可以确认下json和是不是一样的，如果一样就可以。

**Comment by zhu2014yi** [comment]
好的非常感谢
