### ISSUE TITLE
pretrain.model problem

### ISSUE THREAD

**Issue by Soarkey** [researchmm/TracKit#40]
Is `pretrain.model` trained on standard ResNet50? What is the difference with this version https://github.com/ohhhyeahhh/SiamCAR#download-pretrained-backbones?
thanks!

**Comment by JudasDie** [comment]
> Is `pretrain.model` trained on standard ResNet50? What is the difference with this version https://github.com/ohhhyeahhh/SiamCAR#download-pretrained-backbones?
> thanks!
Hi, pls refer to [MCF](https://openaccess.thecvf.com/content_ECCVW_2018/papers/11129/Morimitsu_Multiple_Context_Features_in_Siamese_Networks_for_Visual_Object_Tracking_ECCVW_2018_paper.pdf).
