### ISSUE TITLE
change backbone from resnet to Alexnet

### ISSUE THREAD

**Issue by xiaofeinot** [researchmm/TracKit#41]
Have you ever consider use a Alexnet backbone? Because I found "alex" in the config yaml file.

**Comment by JudasDie** [comment]
> Have you ever consider use a Alexnet backbone? Because I found "alex" in the config yaml file.

Hi, I have trained a model with AlexNet long time ago yet without the feature combination module or the OA module. Anything I can help you?

**Comment by xiaofeinot** [comment]
> > Have you ever consider use a Alexnet backbone? Because I found "alex" in the config yaml file.
> 
> Hi, I have trained a model with AlexNet long time ago yet without the feature combination module or the OA module. Anything I can help you?

Thanks! I am wondering the performance like A, R or EAO on any dateset using AlexNet instead of ResNet. If you can still remember some information, that's will be very helpful. 
By the way, I'm testing Ocean on the embedded device, the time cost of resnet50 is expensive, so I wonder if there is ever a try with Alexnet.

**Comment by JudasDie** [comment]
> > > Have you ever consider use a Alexnet backbone? Because I found "alex" in the config yaml file.
> > 
> > 
> > Hi, I have trained a model with AlexNet long time ago yet without the feature combination module or the OA module. Anything I can help you?
> 
> Thanks! I am wondering the performance like A, R or EAO on any dateset using AlexNet instead of ResNet. If you can still remember some information, that's will be very helpful.
> By the way, I'm testing Ocean on the embedded device, the time cost of resnet50 is expensive, so I wonder if there is ever a try with Alexnet.

Alex--0.33 AlexBig--0.4 on VOT18 (No OA No multi-dilation). That is all I remember. You may try AlexBig in my advice.
