### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by zhu2014yi** [researchmm/TracKit#42]
hi zhipeng：
在编译期间遇到了一个问题请问这个应该怎么解决呢，如下：
(pysot) xxxi@ubuntu:~/Code/TracKit$ python setup.py develop
/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '1.0.rc0' to '1.0rc0'
  warnings.warn(tmpl.format(**locals()))
running develop
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'lib.models.dcn.deform_conv_cuda' extension
Emitting ninja build file /home/zhuyi/Code/TracKit/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packag                                                                     es/torch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7                                                                     /site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/defor                                                                     m_conv_cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF                                                                     _CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -                                                                     D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std                                                                     =c++14
FAILED: /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o
/usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/tor                                                                     ch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-                                                                     packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/deform_conv                                                                     _cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVE                                                                     RSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUD                                                                     A_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_86'
我的配置是RTX3090 cuda11 cudnn8.0

**Comment by JudasDie** [comment]
> hi zhipeng：
> 在编译期间遇到了一个问题请问这个应该怎么解决呢，如下：
> (pysot) xxxi@ubuntu:~/Code/TracKit$ python setup.py develop
> /home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '1.0.rc0' to '1.0rc0'
> warnings.warn(tmpl.format(**locals()))
> running develop
> running egg_info
> writing mmdet.egg-info/PKG-INFO
> writing dependency_links to mmdet.egg-info/dependency_links.txt
> writing top-level names to mmdet.egg-info/top_level.txt
> reading manifest file 'mmdet.egg-info/SOURCES.txt'
> writing manifest file 'mmdet.egg-info/SOURCES.txt'
> running build_ext
> building 'lib.models.dcn.deform_conv_cuda' extension
> Emitting ninja build file /home/zhuyi/Code/TracKit/build/temp.linux-x86_64-3.7/build.ninja...
> Compiling objects...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> [1/2] /usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packag es/torch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7 /site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/defor m_conv_cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF _CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ - D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std =c++14
> FAILED: /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o
> /usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/tor ch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site- packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/deform_conv _cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVE RSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUD A_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
> nvcc fatal : Unsupported gpu architecture 'compute_86'
> 我的配置是RTX3090 cuda11 cudnn8.0

Hi, 应该是CUDA版本有点高。我这边没3090可能没法发现这个问题。

**Comment by JudasDie** [comment]
> > hi zhipeng：
> > 在编译期间遇到了一个问题请问这个应该怎么解决呢，如下：
> > (pysot) xxxi@ubuntu:~/Code/TracKit$ python setup.py develop
> > /home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '1.0.rc0' to '1.0rc0'
> > warnings.warn(tmpl.format(**locals()))
> > running develop
> > running egg_info
> > writing mmdet.egg-info/PKG-INFO
> > writing dependency_links to mmdet.egg-info/dependency_links.txt
> > writing top-level names to mmdet.egg-info/top_level.txt
> > reading manifest file 'mmdet.egg-info/SOURCES.txt'
> > writing manifest file 'mmdet.egg-info/SOURCES.txt'
> > running build_ext
> > building 'lib.models.dcn.deform_conv_cuda' extension
> > Emitting ninja build file /home/zhuyi/Code/TracKit/build/temp.linux-x86_64-3.7/build.ninja...
> > Compiling objects...
> > Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> > [1/2] /usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packag es/torch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7 /site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/defor m_conv_cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF _CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ - D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std =c++14
> > FAILED: /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o
> > /usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/tor ch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site- packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/deform_conv _cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVE RSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUD A_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
> > nvcc fatal : Unsupported gpu architecture 'compute_86'
> > 我的配置是RTX3090 cuda11 cudnn8.0
> 
> Hi, 应该是CUDA版本有点高。我这边没3090可能没法发现这个问题。

另外如果你不用deconv的话，你只编译setup.py最后那个测试VOT的就好。

**Comment by zhu2014yi** [comment]
> > hi zhipeng：
> > 在编译期间遇到了一个问题请问这个应该怎么解决呢，如下：
> > (pysot) xxxi@ubuntu:~/Code/TracKit$ python setup.py develop
> > /home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '1.0.rc0' to '1.0rc0'
> > warnings.warn(tmpl.format(**locals()))
> > running develop
> > running egg_info
> > writing mmdet.egg-info/PKG-INFO
> > writing dependency_links to mmdet.egg-info/dependency_links.txt
> > writing top-level names to mmdet.egg-info/top_level.txt
> > reading manifest file 'mmdet.egg-info/SOURCES.txt'
> > writing manifest file 'mmdet.egg-info/SOURCES.txt'
> > running build_ext
> > building 'lib.models.dcn.deform_conv_cuda' extension
> > Emitting ninja build file /home/zhuyi/Code/TracKit/build/temp.linux-x86_64-3.7/build.ninja...
> > Compiling objects...
> > Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> > [1/2] /usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packag es/torch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7 /site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/defor m_conv_cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF _CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ - D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std =c++14
> > FAILED: /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o
> > /usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/tor ch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site- packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/deform_conv _cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVE RSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUD A_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
> > nvcc fatal : Unsupported gpu architecture 'compute_86'
> > 我的配置是RTX3090 cuda11 cudnn8.0
> 
> Hi, 应该是CUDA版本有点高。我这边没3090可能没法发现这个问题。

你的3090是用的CUDA10 吗

**Comment by zhu2014yi** [comment]
> > > hi zhipeng：
> > > 在编译期间遇到了一个问题请问这个应该怎么解决呢，如下：
> > > (pysot) xxxi@ubuntu:~/Code/TracKit$ python setup.py develop
> > > /home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '1.0.rc0' to '1.0rc0'
> > > warnings.warn(tmpl.format(**locals()))
> > > running develop
> > > running egg_info
> > > writing mmdet.egg-info/PKG-INFO
> > > writing dependency_links to mmdet.egg-info/dependency_links.txt
> > > writing top-level names to mmdet.egg-info/top_level.txt
> > > reading manifest file 'mmdet.egg-info/SOURCES.txt'
> > > writing manifest file 'mmdet.egg-info/SOURCES.txt'
> > > running build_ext
> > > building 'lib.models.dcn.deform_conv_cuda' extension
> > > Emitting ninja build file /home/zhuyi/Code/TracKit/build/temp.linux-x86_64-3.7/build.ninja...
> > > Compiling objects...
> > > Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> > > [1/2] /usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packag es/torch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7 /site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/defor m_conv_cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF _CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ - D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std =c++14
> > > FAILED: /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o
> > > /usr/local/cuda/bin/nvcc -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site-packages/tor ch/include/torch/csrc/api/include -I/home/zhuyi/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/include/TH -I/home/xxxi/anaconda3/envs/pysot/lib/python3.7/site- packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhuyi/anaconda3/envs/pysot/include/python3.7m -c -c /home/xxxi/Code/TracKit/lib/models/dcn/src/deform_conv _cuda_kernel.cu -o /home/xxxi/Code/TracKit/build/temp.linux-x86_64-3.7/lib/models/dcn/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVE RSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUD A_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
> > > nvcc fatal : Unsupported gpu architecture 'compute_86'
> > > 我的配置是RTX3090 cuda11 cudnn8.0
> > 
> > 
> > Hi, 应该是CUDA版本有点高。我这边没3090可能没法发现这个问题。
> 
> 另外如果你不用deconv的话，你只编译setup.py最后那个测试VOT的就好。

好的 ，感谢
