### ISSUE TITLE
eval_vot

### ISSUE THREAD

**Issue by SilvesterSun** [researchmm/TracKit#43]
作者您好，当我在评估vot测验结果的时候，报错如下：
  File "/home/ubuntu/TracKit/lib/eval_toolkit/bin/../../eval_toolkit/pysot/evaluation/eao_benchmark.py", line 110, in _calculate_eao
    max_len = max([len(x) for x in all_overlaps])
ValueError: max() arg is an empty sequence
请问可以解答一下什么原因吗？谢谢

**Comment by xiaofeinot** [comment]
我是单独test，然后再eval的时候可以，但是在Ocean.yaml中设置TEST: ISTRUE: True 以及TUNE:   ISTRUE: True时无法正常的评估和微调，报的错也是max() arg is an empty sequence

**Comment by SilvesterSun** [comment]
好的，谢谢。我也试了，test和eval分开就可以了。





------------------ Original ------------------

**Comment by xiaofeinot** [comment]
> 好的，谢谢。我也试了，test和eval分开就可以了。
> […](#)
> ------------------ Original ------------------ From: xiaofeinot <notifications@github.com&gt; Date: Sat,Oct 31,2020 9:16 AM To: researchmm/TracKit <TracKit@noreply.github.com&gt; Cc: SilvesterSun <983082671@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [researchmm/TracKit] eval_vot (#43) 我是单独test，然后再eval的时候可以，但是在Ocean.yaml中设置TEST: ISTRUE: True 以及TUNE: ISTRUE: True时无法正常的评估和微调，报的错也是max() arg is an empty sequence — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那你可以在某个数据集上微调吗？原作者只给了单独test和eval的命令，没有单独tune的命令

**Comment by kasuo511** [comment]
似乎你需要吧result放到result文件夹里面才能评估

**Comment by X-ray0214** [comment]
> 好的，谢谢。我也试了，test和eval分开就可以了。
> […](#)
> ------------------ Original ------------------ From: xiaofeinot <notifications@github.com&gt; Date: Sat,Oct 31,2020 9:16 AM To: researchmm/TracKit <TracKit@noreply.github.com&gt; Cc: SilvesterSun <983082671@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [researchmm/TracKit] eval_vot (#43) 我是单独test，然后再eval的时候可以，但是在Ocean.yaml中设置TEST: ISTRUE: True 以及TUNE: ISTRUE: True时无法正常的评估和微调，报的错也是max() arg is an empty sequence — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，请问可以详细说一下你是怎么解决的吗？
