### ISSUE TITLE
Which datasets are supported for eval ？

### ISSUE THREAD

**Issue by xiaofeinot** [researchmm/TracKit#44]
If I use "python lib/eval_toolkit/bin/eval.py " to eval the performance of model, which  datasets are supported? Only VOT or some of VOT, OTB, GOT10K, LASOT ? Thanks !

**Comment by JudasDie** [comment]
> If I use "python lib/eval_toolkit/bin/eval.py " to eval the performance of model, which datasets are supported? Only VOT or some of VOT, OTB, GOT10K, LASOT ? Thanks !

Hi, VOT is supported. You can change val benchmark referring to VOT codes.

**Comment by xiaofeinot** [comment]
> > If I use "python lib/eval_toolkit/bin/eval.py " to eval the performance of model, which datasets are supported? Only VOT or some of VOT, OTB, GOT10K, LASOT ? Thanks !
> 
> Hi, VOT is supported. You can change val benchmark referring to VOT codes.

Hi, so that's mean that if I want to eval the tracker in other datasets, I have to refer the VOT codes and write codes myself? Is it right?

**Comment by JudasDie** [comment]
> > > If I use "python lib/eval_toolkit/bin/eval.py " to eval the performance of model, which datasets are supported? Only VOT or some of VOT, OTB, GOT10K, LASOT ? Thanks !
> > 
> > 
> > Hi, VOT is supported. You can change val benchmark referring to VOT codes.
> 
> Hi, so that's mean that if I want to eval the tracker in other datasets, I have to refer the VOT codes and write codes myself? Is it right?

Yes. In fact, only small changes are expected.
