### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by kasuo511** [researchmm/TracKit#45]
Hi Zhipeng
![20201031170314](https://user-images.githubusercontent.com/19659016/97775708-dc9ca180-1b9d-11eb-813a-bfa35ba0869e.png)

It seems that I can not setup the conda env successfully, help me pls. Thanks!

**Comment by JudasDie** [comment]
> Hi Zhipeng
> ![20201031170314](https://user-images.githubusercontent.com/19659016/97775708-dc9ca180-1b9d-11eb-813a-bfa35ba0869e.png)
> 
> It seems that I can not setup the conda env successfully, help me pls. Thanks!

Hi, there is a `permission denied` in your log. So pls change the permission of the directory and re-install deconv with `python setup.py develop`.

**Comment by kasuo511** [comment]
> > Hi Zhipeng
> > ![20201031170314](https://user-images.githubusercontent.com/19659016/97775708-dc9ca180-1b9d-11eb-813a-bfa35ba0869e.png)
> > It seems that I can not setup the conda env successfully, help me pls. Thanks!
> 
> Hi, there is a `permission denied` in your log. So pls change the permission of the directory and re-install deconv with `python setup.py develop`.

Thanks for the reply, fixed the permission problem. While the problem `NameError: name 'DeformConv' is not defined` still exists.

**Comment by kasuo511** [comment]
Solved by manually import file deform in the subfolder.

**Comment by HaziqRazali** [comment]
> Solved by manually import file deform in the subfolder.

could you tell me how and where you did the import? What did you write and in which specific file?

**Comment by kokapelli** [comment]
> > Solved by manually import file deform in the subfolder.
> 
> could you tell me how and where you did the import? What did you write and in which specific file?

I managed to bypass this issue by adding the following import to connect.py:
`from .dcn.deform_conv import DeformConv`
That or you could perhaps add it to the empty __init__.py file in lib/models/
