### ISSUE TITLE
only VOT test jsons

### ISSUE THREAD

**Issue by xiaofeinot** [researchmm/TracKit#46]
Hi! From the google drive link, I can only find the VOT2018 and VOT2019 test json. If I want to, for example, test the tracker in OTB100, where can I find the corresponding json file？

**Comment by JudasDie** [comment]
> Hi! From the google drive link, I can only find the VOT2018 and VOT2019 test json. If I want to, for example, test the tracker in OTB100, where can I find the corresponding json file？

Hi, I have uploaded them now, pls check it.
