### ISSUE TITLE
Testing and training stuck problem

### ISSUE THREAD

**Issue by kasuo511** [researchmm/TracKit#48]
Hi, Zhipeng
When I test the tracker or train it, the program always stuck or jumped out. Could you pls help me with it?
when `python tracking/test_ocean.py --arch Ocean --resume snapshot/OceanV.pth --dataset VOT2019`:

![segmentation](https://user-images.githubusercontent.com/19659016/98089730-21864800-1ebe-11eb-8369-26b4fc4d1f09.png)

It just jumps out and does nothing.

when `python tracking/onekey.py` or `python ./tracking/train_ocean.py --cfg experiments/train/Ocean.yaml --gpus 0 --workers 32 2>&1 | tee logs/Ocean_train.log`:

![stuck in train](https://user-images.githubusercontent.com/19659016/98089876-4bd80580-1ebe-11eb-9a1e-7e273ae5cc60.png)

It stuck and does not work.

the GPU status for a long time:

![GPU state](https://user-images.githubusercontent.com/19659016/98089886-4ed2f600-1ebe-11eb-893e-5d781cc96475.png)

**Comment by JudasDie** [comment]
> Hi, Zhipeng
> When I test the tracker or train it, the program always stuck or jumped out. Could you pls help me with it?
> when `python tracking/test_ocean.py --arch Ocean --resume snapshot/OceanV.pth --dataset VOT2019`:
> 
> ![segmentation](https://user-images.githubusercontent.com/19659016/98089730-21864800-1ebe-11eb-8369-26b4fc4d1f09.png)
> 
> It just jumps out and does nothing.
> 
> when `python tracking/onekey.py` or `python ./tracking/train_ocean.py --cfg experiments/train/Ocean.yaml --gpus 0 --workers 32 2>&1 | tee logs/Ocean_train.log`:
> 
> ![stuck in train](https://user-images.githubusercontent.com/19659016/98089876-4bd80580-1ebe-11eb-9a1e-7e273ae5cc60.png)
> 
> It stuck and does not work.
> 
> the GPU status for a long time:
> 
> ![GPU state](https://user-images.githubusercontent.com/19659016/98089886-4ed2f600-1ebe-11eb-893e-5d781cc96475.png)

Hi, for testing, it seems that there are some errors in you env or machine, and for training, pls try to decrease the number of workers.
