### ISSUE TITLE
about vot2020 eao

### ISSUE THREAD

**Issue by kongbia** [researchmm/TracKit#49]
我使用提供的MSS模型在vot2020上测试eao只有0.430，我用的测试工具是0.4.2的版本，pytorch1.3，是环境问题造成的吗

**Comment by JudasDie** [comment]
> 我使用提供的MSS模型在vot2020上测试eao只有0.430，我用的测试工具是0.4.2的版本，pytorch1.3，是环境问题造成的吗

是的，麻烦按照install里面版本安装vot-toolkit
