### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by zhu2014yi** [researchmm/TracKit#5]
hi zhipeng,请问是否有打算将训练数据集上传百度云盘

**Comment by JudasDie** [comment]
> hi zhipeng,请问是否有打算将训练数据集上传百度云盘

hi, 可能要到回校我试试行不行。现在百度云上载速度太慢了。谷歌云里面我有切成小文件的，如果大文件不好下载你可以试试小文件。

**Comment by zhu2014yi** [comment]
> > hi zhipeng,请问是否有打算将训练数据集上传百度云盘
> 
> hi, 可能要到回校我试试行不行。现在百度云上载速度太慢了。谷歌云里面我有切成小文件的，如果大文件不好下载你可以试试小文件。
好的，非常感谢
