### ISSUE TITLE
LASOT testing

### ISSUE THREAD

**Issue by UmarSpa** [researchmm/TracKit#50]
Hi,

In the [tutorial](https://github.com/researchmm/TracKit/blob/master/lib/tutorial/Ocean/ocean.md) for Ocean, you mentioned that the testing can be done on LASOT as well. But you don't provide the corresponding yaml file (`/experiments/test/LASOT/Ocean.yaml`). 

Can you share this yaml file, please ?

**Comment by UmarSpa** [comment]
Any update on this will  be very much appreciated 

@JudasDie @penghouwen

**Comment by JudasDie** [comment]
> Any update on this will be very much appreciated
> 
> @JudasDie @penghouwen

Hi, I would update it this week.

**Comment by JudasDie** [comment]
> > Any update on this will be very much appreciated
> > @JudasDie @penghouwen
> 
> Hi, I would update it this week.

Updated, pls download the corresponding model from GoogleDrive (see ocean.md)
