### ISSUE TITLE
运行tune_tpe提示CUDA out of memory

### ISSUE THREAD

**Issue by dasdassssss** [researchmm/TracKit#51]
您好，我用一张GPU尝试tune_tpe，跑了几个小时候显示：RuntimeError: CUDA out of memory. Tried to allocate 90.00 MiB (GPU 0; 10.76 GiB total capacity; 6.31 GiB already allocated; 22.12 MiB free; 6.36 GiB reserved in total by PyTorch)
请问，对于tune tpe一张显卡是否不够用？

**Comment by JudasDie** [comment]
> 您好，我用一张GPU尝试tune_tpe，跑了几个小时候显示：RuntimeError: CUDA out of memory. Tried to allocate 90.00 MiB (GPU 0; 10.76 GiB total capacity; 6.31 GiB already allocated; 22.12 MiB free; 6.36 GiB reserved in total by PyTorch)
> 请问，对于tune tpe一张显卡是否不够用？

一张卡比较久，一般是4-8.你可以把trails调小点。
