### ISSUE TITLE
Any plan to add test code for VOT-LT dataset?

### ISSUE THREAD

**Issue by xiaofeinot** [researchmm/TracKit#52]
I noticed that there're eval code for VOT2018-LT dataset in lib/eval_toolkit. However, the repo can't test on the VOT-LT datasets and get the results. If the test code can be implemented, it will be of good use for us freshers to learn and use the repo as a base element to develop individual research. Thanks!

**Comment by JudasDie** [comment]
> I noticed that there're eval code for VOT2018-LT dataset in lib/eval_toolkit. However, the repo can't test on the VOT-LT datasets and get the results. If the test code can be implemented, it will be of good use for us freshers to learn and use the repo as a base element to develop individual research. Thanks!

Hi, thanks for your advice. Since LT considers re-detection, the code now does support that. We may update it later.
