### ISSUE TITLE
change the BATCH in Ocean.yaml will cause a probleam?

### ISSUE THREAD

**Issue by asdnima2007** [researchmm/TracKit#53]
the message is 
  File "/home/wzw/TracKit/tracking/../lib/models/ocean.py", line 328, in forward
    bbox_pred_to_img = self.pred_to_image(bbox_pred)
  File "/home/wzw/TracKit/tracking/../lib/models/ocean.py", line 150, in pred_to_image
    pred_x1 = self.grid_to_search_x - bbox_pred[:, 0, ...].unsqueeze(1)  # 17*17
RuntimeError: The size of tensor a (32) must match the size of tensor b (5) at non-singleton dimension 0
thank u for your help

**Comment by UmarSpa** [comment]
The problem is that the batch is size is hard coded. In order to make the code work, you need to change the batch size manually in line 21 of `/lib/models/ocean.py`

        self.batch = 32 if self.training else 1

**Comment by JudasDie** [comment]
> the message is
> File "/home/wzw/TracKit/tracking/../lib/models/ocean.py", line 328, in forward
> bbox_pred_to_img = self.pred_to_image(bbox_pred)
> File "/home/wzw/TracKit/tracking/../lib/models/ocean.py", line 150, in pred_to_image
> pred_x1 = self.grid_to_search_x - bbox_pred[:, 0, ...].unsqueeze(1) # 17*17
> RuntimeError: The size of tensor a (32) must match the size of tensor b (5) at non-singleton dimension 0
> thank u for your help

Hi, if you use `OA`, pls consider changing `lib/models/ocean.py` line21. If you do not use `OA`, it may not be a problem.
