### ISSUE TITLE
SiamDW pretraining

### ISSUE THREAD

**Issue by lpuglia** [researchmm/TracKit#54]
Hello, thanks for the wonderful research project.

At the moment I'm looking into SiamDW code. So far i didn't find any details on what the pretraining procedure consists of. In particular, how do you obtain `snapshot/siamdw_res22w.pth` checkpoint? (referenced here: https://github.com/researchmm/TracKit/blob/master/lib/tutorial/SiamDW/siamdw.md)

I have some experience with pretraining on Imagenet for detection transfer-learning (I can see it is the case for Ocean https://github.com/researchmm/TracKit/blob/master/lib/tutorial/Ocean/ocean.md#Training).

What dataset do you use to get a good initialization of the weights for the SiamDW-Tracking training?

**Comment by JudasDie** [comment]
> Hello, thanks for the wonderful research project.
> 
> At the moment I'm looking into SiamDW code. So far i didn't find any details on what the pretraining procedure consists of. In particular, how do you obtain `snapshot/siamdw_res22w.pth` checkpoint? (referenced here: https://github.com/researchmm/TracKit/blob/master/lib/tutorial/SiamDW/siamdw.md)
> 
> I have some experience with pretraining on Imagenet for detection transfer-learning (I can see it is the case for Ocean https://github.com/researchmm/TracKit/blob/master/lib/tutorial/Ocean/ocean.md#Training).
> 
> What dataset do you use to get a good initialization of the weights for the SiamDW-Tracking training?

Hi, I have updated the readme. Please check that.

**Comment by lpuglia** [comment]
Hello, thanks for the answer, probably i was not clear enough, but what i was asking for is how to pretrain the model in the first place. The new instructions state:

```
1. Download pretrain model from here and put it in pretrain (named with pretrain.model).
```

What I would like to know is the procedure (training+dataset+model modification) to train the model from scratch myself, do you have any details on that?

**Comment by JudasDie** [comment]
> Hello, thanks for the answer, probably i was not clear enough, but what i was asking for is how to pretrain the model in the first place. The new instructions state:
> 
> ```
> 1. Download pretrain model from here and put it in pretrain (named with pretrain.model).
> ```
> 
> What I would like to know is the procedure (training+dataset+model modification) to train the model from scratch myself, do you have any details on that?

The pertaining process follows classical Imagenet training, referring to [here](https://github.com/pytorch/examples/tree/master/imagenet).
