### ISSUE TITLE
VOT2018 result

### ISSUE THREAD

**Issue by github-aaliu** [researchmm/TracKit#56]
i remove scale,ratio penalty and lr, only keep cos window, the VOT2018 result debase 6%, is there operate so important?

**Comment by JudasDie** [comment]
> i remove scale,ratio penalty and lr, only keep cos window, the VOT2018 result debase 6%, is there operate so important?

Yes, you may have realized that almost all tracking methods (CF or Siamese) have these post-processing techniches.  This may be a potential research direction.
