### ISSUE TITLE
KeyError during Ocean traning and testing

### ISSUE THREAD

**Issue by interflow-miao** [researchmm/TracKit#57]
Dear author，i meet a KeyError when i try to run the test_ocean.py
the whole error message as bellow:
(TracKit) @root:~/tracking/TracKit-master$ python tracking/test_ocean.py --arch Ocean --resume snapshot/OceanO.pth --dataset VOT2019
Traceback (most recent call last):
  File "tracking/test_ocean.py", line 386, in <module>
    main()
  File "tracking/test_ocean.py", line 197, in main
    siam_net = models.__dict__[args.arch](align=siam_info.align, online=args.online)
KeyError: 'Ocean'

if i try to run with the default config like: python test_ocean,the KetError still exist like :KeyError: 'OceanTRT'
and when i try to run train_ocean,the same problem arises.
Is there a problem with the command I typed?what can i do to solve this problem.
Any answers will be greatly appreciated

**Comment by interflow-miao** [comment]
> Dear author，i meet a KeyError when i try to run the test_ocean.py
> the whole error message as bellow:
> (TracKit) @root:~/tracking/TracKit-master$ python tracking/test_ocean.py --arch Ocean --resume snapshot/OceanO.pth --dataset VOT2019
> Traceback (most recent call last):
> File "tracking/test_ocean.py", line 386, in
> main()
> File "tracking/test_ocean.py", line 197, in main
> siam_net = models.**dict**[args.arch](align=siam_info.align, online=args.online)
> KeyError: 'Ocean'
> 
> if i try to run with the default config like: python test_ocean,the KetError still exist like :KeyError: 'OceanTRT'
> and when i try to run train_ocean,the same problem arises.
> Is there a problem with the command I typed?what can i do to solve this problem.
> Any answers will be greatly appreciated

oky， I have solved the problem,thank you~

**Comment by JudasDie** [comment]
> > Dear author，i meet a KeyError when i try to run the test_ocean.py
> > the whole error message as bellow:
> > (TracKit) @root:~/tracking/TracKit-master$ python tracking/test_ocean.py --arch Ocean --resume snapshot/OceanO.pth --dataset VOT2019
> > Traceback (most recent call last):
> > File "tracking/test_ocean.py", line 386, in
> > main()
> > File "tracking/test_ocean.py", line 197, in main
> > siam_net = models.**dict**[args.arch](align=siam_info.align, online=args.online)
> > KeyError: 'Ocean'
> > if i try to run with the default config like: python test_ocean,the KetError still exist like :KeyError: 'OceanTRT'
> > and when i try to run train_ocean,the same problem arises.
> > Is there a problem with the command I typed?what can i do to solve this problem.
> > Any answers will be greatly appreciated
> 
> oky， I have solved the problem,thank you~
