### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by huangwanghuiYY** [researchmm/TracKit#6]
hi zhipeng,

      从你上篇工作SiamDW就开始关注你了，你的视频讲解也非常棒，看到你新工作赶紧来follow了~哈哈。

      切入正题，我看你数据集最终形式是xxx_crop511的，后续会考虑更新开源相关代码或工具，让我们直接从本地已有各个数据集（如GOT10K）crop出图像对吗（也就是最终生成你提供的xxx_crop511形式数据集）？

      感谢回复！

**Comment by JudasDie** [comment]
> hi zhipeng,
> 
> ```
>   从你上篇工作SiamDW就开始关注你了，你的视频讲解也非常棒，看到你新工作赶紧来follow了~哈哈。
> 
>   切入正题，我看你数据集最终形式是xxx_crop511的，后续会考虑更新开源相关代码或工具，让我们直接从本地已有各个数据集（如GOT10K）crop出图像对吗（也就是最终生成你提供的xxx_crop511形式数据集）？
> 
>   感谢回复！
> ```

hi, 承蒙厚爱，谢谢关注我们工作哈。crop的脚本SiamDW里面有一个示例，加新的数据集时候参考那个改就可以。我后面整理下把各个数据集crop的代码放到这个仓库里。

**Comment by huangwanghuiYY** [comment]
谢谢志鹏，争取赶紧follow你工作整出篇论文哈哈，增加个小小的citation 😄

**Comment by JudasDie** [comment]
> 谢谢志鹏，争取赶紧follow你工作整出篇论文哈哈，增加个小小的citation 😄

加油加油！一起进步。

**Comment by JudasDie** [comment]
> > 谢谢志鹏，争取赶紧follow你工作整出篇论文哈哈，增加个小小的citation 😄
> 
> 加油加油！一起进步。



> > 谢谢志鹏，争取赶紧follow你工作整出篇论文哈哈，增加个小小的citation 😄
> 
> 加油加油！一起进步。

Hi, I have uploaded the cropping scripts in `lib/dataset/crop`. Some additional datasets, e.g. LaSOT, RGBT210, RGBT234, visdrone, are also provided. Hope this help your work.
