### ISSUE TITLE
获取VOT2020.json文件

### ISSUE THREAD

**Issue by sysu-shey** [researchmm/TracKit#60]
您好，请问您方便提供VOT2020.json文件么？我只能从官网的code获取description.json文件~谢谢！ @Sy-Zhang @FuzhiYang @bei21 @HYPJUDY @ZhichengHuang

**Comment by JudasDie** [comment]
> 您好，请问您方便提供VOT2020.json文件么？我只能从官网的code获取description.json文件~谢谢！ @Sy-Zhang @FuzhiYang @bei21 @HYPJUDY @ZhichengHuang

你好，VOT2020和之前数据集已经评测方式都不一样哈，暂时只能用官方toolkit测试，你可以参考我们库里面给Ocean+的接口看看如何写自己算法和官方toolkit的接口。另外上面@的都不是论文作者哈，@我就好了。

**Comment by sysu-shey** [comment]
好的好的，我去看看参考下，感谢您！
