### ISSUE TITLE
TrackingNet support

### ISSUE THREAD

**Issue by SilvioGiancola** [researchmm/TracKit#61]
Dear team, 

Thank you for sharing your code, it is great for the tracking community.
Do you have any plan on including experiments/benchmarks on [TrackingNet](https://github.com/SilvioGiancola/TrackingNet-devkit)?

Please let me know,

Best,

**Comment by penghouwen** [comment]
Hi @SilvioGiancola ,

Glad to hear from you. We're interested in integrating Ocean and TracKit toolkit into the wide-used TrackingNet.
@JudasDie  Zhipeng, would you help to discuss with @SilvioGiancola on the integration? Thanks.

Thanks,
Houwen

**Comment by JudasDie** [comment]
> Dear team,
> 
> Thank you for sharing your code, it is great for the tracking community.
> Do you have any plan on including experiments/benchmarks on [TrackingNet](https://github.com/SilvioGiancola/TrackingNet-devkit)?
> 
> Please let me know,
> 
> Best,

Hi, thanks for your interest. The results and testing script would be updated this week.

**Comment by SilvioGiancola** [comment]
Thanks @penghouwen and @JudasDie for your feedback! Any update on your side?

If that can be of any help, a [pip package for TrackingNet](https://pypi.org/project/TrackingNet/) is now available. It integrates functions to retrieve the IDs of specific tracking sequences in training and testing as well as API calls to download the sequences.

If you are facing any issue in using those API, please feel free to reach out.

Best,

**Comment by JudasDie** [comment]
> Thanks @penghouwen and @JudasDie for your feedback! Any update on your side?
> 
> If that can be of any help, a [pip package for TrackingNet](https://pypi.org/project/TrackingNet/) is now available. It integrates functions to retrieve the IDs of specific tracking sequences in training and testing as well as API calls to download the sequences.
> 
> If you are facing any issue in using those API, please feel free to reach out.
> 
> Best,

I plan to integrate a testing script like `lib/core/eval_otb.py`. Is that ok for your need? (sorry for the late update, I'm busy with other projects recently)
