### ISSUE TITLE
About Tune on OTB100

### ISSUE THREAD

**Issue by jianjiandandande** [researchmm/TracKit#67]
By executing tracking/tune_tpe.py to search the parameters of OTB100, the last_result in the generated experiment_state-2021-01-20_01-31-36. json is empty, and the search result of the VOT data set is normal
![tune_error](https://user-images.githubusercontent.com/15951818/105115286-791e7200-5b03-11eb-96b7-d129d73f1305.png)

**Comment by JudasDie** [comment]
> By executing tracking/tune_tpe.py to search the parameters of OTB100, the last_result in the generated experiment_state-2021-01-20_01-31-36. json is empty, and the search result of the VOT data set is normal
> ![tune_error](https://user-images.githubusercontent.com/15951818/105115286-791e7200-5b03-11eb-96b7-d129d73f1305.png)

hello, I could not open the image. Could you copy its content or sent this image to my mail?

**Comment by jianjiandandande** [comment]
> > By executing tracking/tune_tpe.py to search the parameters of OTB100, the last_result in the generated experiment_state-2021-01-20_01-31-36. json is empty, and the search result of the VOT data set is normal
> > ![tune_error](https://user-images.githubusercontent.com/15951818/105115286-791e7200-5b03-11eb-96b7-d129d73f1305.png)
> 
> hello, I could not open the image. Could you copy its content or sent this image to my mail?

```json
{
      "trainable_name": "fitness",
      "trial_id": "64eef684",
      "config": {
        "big_sz": 303,
        "penalty_k": 0.07100000000000001,
        "ratio": 1,
        "scale_lr": 0.524,
        "small_sz": 255,
        "window_influence": 0.591
      },
      "local_dir": "/Vincent2/ocean_update/TPE_results/zp_tune",
      "evaluated_params": {
        "big_sz": 303,
        "penalty_k": 0.07100000000000001,
        "ratio": 1,
        "scale_lr": 0.524,
        "small_sz": 255,
        "window_influence": 0.591
      },
      "experiment_tag": "1_big_sz=303,penalty_k=0.071,ratio=1,scale_lr=0.524,small_sz=255,window_influence=0.591",
      "location": {
        "_type": "CLOUDPICKLE_FALLBACK",
        "value": "8004953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e"
      },
      "resources": {
        "cpu": 1,
        "gpu": 0.12,
        "memory": 0,
        "object_store_memory": 0,
        "extra_cpu": 0,
        "extra_gpu": 0,
        "extra_memory": 0,
        "extra_object_store_memory": 0,
        "custom_resources": {},
        "extra_custom_resources": {}
      },
      "stopping_criterion": {
        "AUC": 0.8
      },
      "loggers": "80044e2e",
      "sync_to_driver_fn": "80044e2e",
      "verbose": true,
      "max_failures": 0,
      "last_result": {},
      "last_update_time": -Infinity,
      "metric_analysis": {},
      "n_steps": [
        5,
        10
      ],
      "metric_n_steps": {},
      "export_formats": [],
      "status": "ERROR",
      "start_time": 1611038504.4663675,
      "logdir": "/Vincent2/ocean_update/TPE_results/zp_tune/fitness_1_big_sz=303,penalty_k=0.071,ratio=1,scale_lr=0.524,small_sz=255,window_influence=0.591_2021-01-19_06-41-44poxjnq23",
      "runner": null,
      "result_logger": null,
      "last_debug": 0,
      "error_file": null,
      "error_msg": null,
      "custom_trial_name": null,
      "saving_to": null,
      "remote_checkpoint_dir_prefix": null,
      "checkpoint_freq": 0,
      "checkpoint_at_end": false,
      "sync_on_checkpoint": true,
      "checkpoint_manager": {
        "_type": "CLOUDPICKLE_FALLBACK",
        "value": "80049565010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c186e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e"
      },
      "restore_path": null,
      "restoring_from": null,
      "num_failures": 0,
      "results": "80044e2e",
      "best_result": "80044e2e",
      "param_config": "80044e2e",
      "extra_arg": "80044e2e",
      "_nonjson_fields": [
        "loggers",
        "sync_to_driver_fn",
        "results",
        "best_result",
        "param_config",
        "extra_arg"
      ],
      "resuming_from": null,
      "__logger_started__": true
    },
```
hi, is that all right?

**Comment by JudasDie** [comment]
> By executing tracking/tune_tpe.py to search the parameters of OTB100, the last_result in the generated experiment_state-2021-01-20_01-31-36. json is empty, and the search result of the VOT data set is normal
> ![tune_error](https://user-images.githubusercontent.com/15951818/105115286-791e7200-5b03-11eb-96b7-d129d73f1305.png)



> > > By executing tracking/tune_tpe.py to search the parameters of OTB100, the last_result in the generated experiment_state-2021-01-20_01-31-36. json is empty, and the search result of the VOT data set is normal
> > > ![tune_error](https://user-images.githubusercontent.com/15951818/105115286-791e7200-5b03-11eb-96b7-d129d73f1305.png)
> > 
> > 
> > hello, I could not open the image. Could you copy its content or sent this image to my mail?
> 
> ```json
> {
>       "trainable_name": "fitness",
>       "trial_id": "64eef684",
>       "config": {
>         "big_sz": 303,
>         "penalty_k": 0.07100000000000001,
>         "ratio": 1,
>         "scale_lr": 0.524,
>         "small_sz": 255,
>         "window_influence": 0.591
>       },
>       "local_dir": "/Vincent2/ocean_update/TPE_results/zp_tune",
>       "evaluated_params": {
>         "big_sz": 303,
>         "penalty_k": 0.07100000000000001,
>         "ratio": 1,
>         "scale_lr": 0.524,
>         "small_sz": 255,
>         "window_influence": 0.591
>       },
>       "experiment_tag": "1_big_sz=303,penalty_k=0.071,ratio=1,scale_lr=0.524,small_sz=255,window_influence=0.591",
>       "location": {
>         "_type": "CLOUDPICKLE_FALLBACK",
>         "value": "8004953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e"
>       },
>       "resources": {
>         "cpu": 1,
>         "gpu": 0.12,
>         "memory": 0,
>         "object_store_memory": 0,
>         "extra_cpu": 0,
>         "extra_gpu": 0,
>         "extra_memory": 0,
>         "extra_object_store_memory": 0,
>         "custom_resources": {},
>         "extra_custom_resources": {}
>       },
>       "stopping_criterion": {
>         "AUC": 0.8
>       },
>       "loggers": "80044e2e",
>       "sync_to_driver_fn": "80044e2e",
>       "verbose": true,
>       "max_failures": 0,
>       **"last_result": {},**
>       "last_update_time": -Infinity,
>       "metric_analysis": {},
>       "n_steps": [
>         5,
>         10
>       ],
>       "metric_n_steps": {},
>       "export_formats": [],
>       "status": "ERROR",
>       "start_time": 1611038504.4663675,
>       "logdir": "/Vincent2/ocean_update/TPE_results/zp_tune/fitness_1_big_sz=303,penalty_k=0.071,ratio=1,scale_lr=0.524,small_sz=255,window_influence=0.591_2021-01-19_06-41-44poxjnq23",
>       "runner": null,
>       "result_logger": null,
>       "last_debug": 0,
>       "error_file": null,
>       "error_msg": null,
>       "custom_trial_name": null,
>       "saving_to": null,
>       "remote_checkpoint_dir_prefix": null,
>       "checkpoint_freq": 0,
>       "checkpoint_at_end": false,
>       "sync_on_checkpoint": true,
>       "checkpoint_manager": {
>         "_type": "CLOUDPICKLE_FALLBACK",
>         "value": "80049565010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c186e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e"
>       },
>       "restore_path": null,
>       "restoring_from": null,
>       "num_failures": 0,
>       "results": "80044e2e",
>       "best_result": "80044e2e",
>       "param_config": "80044e2e",
>       "extra_arg": "80044e2e",
>       "_nonjson_fields": [
>         "loggers",
>         "sync_to_driver_fn",
>         "results",
>         "best_result",
>         "param_config",
>         "extra_arg"
>       ],
>       "resuming_from": null,
>       "__logger_started__": true
>     },
> ```
> 
> hi, is that all right? And the -Infinity is very strange

Could you paste the `tune_tpe.log`? There should be a file in `logs`?

**Comment by jianjiandandande** [comment]
> > By executing tracking/tune_tpe.py to search the parameters of OTB100, the last_result in the generated experiment_state-2021-01-20_01-31-36. json is empty, and the search result of the VOT data set is normal
> > ![tune_error](https://user-images.githubusercontent.com/15951818/105115286-791e7200-5b03-11eb-96b7-d129d73f1305.png)
> 
> > > > By executing tracking/tune_tpe.py to search the parameters of OTB100, the last_result in the generated experiment_state-2021-01-20_01-31-36. json is empty, and the search result of the VOT data set is normal
> > > > ![tune_error](https://user-images.githubusercontent.com/15951818/105115286-791e7200-5b03-11eb-96b7-d129d73f1305.png)
> > > 
> > > 
> > > hello, I could not open the image. Could you copy its content or sent this image to my mail?
> > 
> > 
> > ```json
> > {
> >       "trainable_name": "fitness",
> >       "trial_id": "64eef684",
> >       "config": {
> >         "big_sz": 303,
> >         "penalty_k": 0.07100000000000001,
> >         "ratio": 1,
> >         "scale_lr": 0.524,
> >         "small_sz": 255,
> >         "window_influence": 0.591
> >       },
> >       "local_dir": "/Vincent2/ocean_update/TPE_results/zp_tune",
> >       "evaluated_params": {
> >         "big_sz": 303,
> >         "penalty_k": 0.07100000000000001,
> >         "ratio": 1,
> >         "scale_lr": 0.524,
> >         "small_sz": 255,
> >         "window_influence": 0.591
> >       },
> >       "experiment_tag": "1_big_sz=303,penalty_k=0.071,ratio=1,scale_lr=0.524,small_sz=255,window_influence=0.591",
> >       "location": {
> >         "_type": "CLOUDPICKLE_FALLBACK",
> >         "value": "8004953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e"
> >       },
> >       "resources": {
> >         "cpu": 1,
> >         "gpu": 0.12,
> >         "memory": 0,
> >         "object_store_memory": 0,
> >         "extra_cpu": 0,
> >         "extra_gpu": 0,
> >         "extra_memory": 0,
> >         "extra_object_store_memory": 0,
> >         "custom_resources": {},
> >         "extra_custom_resources": {}
> >       },
> >       "stopping_criterion": {
> >         "AUC": 0.8
> >       },
> >       "loggers": "80044e2e",
> >       "sync_to_driver_fn": "80044e2e",
> >       "verbose": true,
> >       "max_failures": 0,
> >       **"last_result": {},**
> >       "last_update_time": -Infinity,
> >       "metric_analysis": {},
> >       "n_steps": [
> >         5,
> >         10
> >       ],
> >       "metric_n_steps": {},
> >       "export_formats": [],
> >       "status": "ERROR",
> >       "start_time": 1611038504.4663675,
> >       "logdir": "/Vincent2/ocean_update/TPE_results/zp_tune/fitness_1_big_sz=303,penalty_k=0.071,ratio=1,scale_lr=0.524,small_sz=255,window_influence=0.591_2021-01-19_06-41-44poxjnq23",
> >       "runner": null,
> >       "result_logger": null,
> >       "last_debug": 0,
> >       "error_file": null,
> >       "error_msg": null,
> >       "custom_trial_name": null,
> >       "saving_to": null,
> >       "remote_checkpoint_dir_prefix": null,
> >       "checkpoint_freq": 0,
> >       "checkpoint_at_end": false,
> >       "sync_on_checkpoint": true,
> >       "checkpoint_manager": {
> >         "_type": "CLOUDPICKLE_FALLBACK",
> >         "value": "80049565010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c186e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e"
> >       },
> >       "restore_path": null,
> >       "restoring_from": null,
> >       "num_failures": 0,
> >       "results": "80044e2e",
> >       "best_result": "80044e2e",
> >       "param_config": "80044e2e",
> >       "extra_arg": "80044e2e",
> >       "_nonjson_fields": [
> >         "loggers",
> >         "sync_to_driver_fn",
> >         "results",
> >         "best_result",
> >         "param_config",
> >         "extra_arg"
> >       ],
> >       "resuming_from": null,
> >       "__logger_started__": true
> >     },
> > ```
> > 
> > 
> > hi, is that all right? And the -Infinity is very strange
> 
> Could you paste the `tune_tpe.log`? There should be a file in `logs`?

I send some file to your email.

**Comment by jianjiandandande** [comment]
i find the reason, https://github.com/researchmm/TracKit/blob/c01f5fd6d27194678098d5382721012901926751/tracking/test_ocean.py#L356
the method **eval_auc_tune** has no guide package.

**Comment by JudasDie** [comment]
> i find the reason,
> 
> https://github.com/researchmm/TracKit/blob/c01f5fd6d27194678098d5382721012901926751/tracking/test_ocean.py#L356
> 
> 
> the method **eval_auc_tune** has no guide package.

Thanks @jianjiandandande  for your fixing!
