### ISSUE TITLE
Feature Extraction 中backbone的输出map大小与论文中不一致？

### ISSUE THREAD

**Issue by codylcs** [researchmm/TracKit#69]
![image](https://user-images.githubusercontent.com/48380363/105439419-ccc5c280-5c9f-11eb-9af6-3279e2e0720d.png)
论文中分别输出的是7x7x1024和31x31x1024，而实际输出却是15x15x1024？

**Comment by JudasDie** [comment]
> ![image](https://user-images.githubusercontent.com/48380363/105439419-ccc5c280-5c9f-11eb-9af6-3279e2e0720d.png)
> 论文中分别输出的是7_7_1024和31_31_1024，而实际输出却是15_15_1024？

z对应的是原本输出是15*15，crop出来中间的7*7

**Comment by codylcs** [comment]
> > ![image](https://user-images.githubusercontent.com/48380363/105439419-ccc5c280-5c9f-11eb-9af6-3279e2e0720d.png)
> > 论文中分别输出的是7_7_1024和31_31_1024，而实际输出却是15_15_1024？
> 
> z对应的是原本输出是15_15，crop出来中间的7_7

经过self.neck后是7x7对吧？抱歉哈，看到论文中的图有点误解^.^

**Comment by JudasDie** [comment]
> > > ![image](https://user-images.githubusercontent.com/48380363/105439419-ccc5c280-5c9f-11eb-9af6-3279e2e0720d.png)
> > > 论文中分别输出的是7_7_1024和31_31_1024，而实际输出却是15_15_1024？
> > 
> > 
> > z对应的是原本输出是15_15，crop出来中间的7_7
> 
> 经过self.neck后是7x7对吧？抱歉哈，看到论文中的图有点误解^.^

嗯嗯对的，可以以code为准，论文图可能不能写出所有特别细节的。

**Comment by codylcs** [comment]
题外，想了解下，OCEAN的速度测试可以到168FPS？在1080ti设备可以到多少？这个转容易转到libtorch或者tensorrt吗？因为看到用的后续想沿着速度方向做点优化

**Comment by JudasDie** [comment]
> 题外，想了解下，OCEAN的速度测试可以到168FPS？在1080ti设备可以到多少？这个转容易转到libtorch或者tensorrt吗？因为看到用的后续想沿着速度方向做点优化

TRT加速可以达到100多，我那个是测了一个500frame的视频[OTB中]。1080ti我没有测试，之前在上面配TRT没成功，现在都用的2080ti我这边。

**Comment by codylcs** [comment]
> > 题外，想了解下，OCEAN的速度测试可以到168FPS？在1080ti设备可以到多少？这个转容易转到libtorch或者tensorrt吗？因为看到用的后续想沿着速度方向做点优化
> 
> TRT加速可以达到100多，我那个是测了一个500frame的视频[OTB中]。1080ti我没有测试，之前在上面配TRT没成功，现在都用的2080ti我这边。

之前看您的bili视频，讲的是要往简洁以及方便落地上靠，感觉看整个代码框架还是有点懵，训练的batchsize=32写死了，模型暂时不支持cpu测试，后续会持续在OCEAN上做优化吗？感谢

**Comment by JudasDie** [comment]
> > > 题外，想了解下，OCEAN的速度测试可以到168FPS？在1080ti设备可以到多少？这个转容易转到libtorch或者tensorrt吗？因为看到用的后续想沿着速度方向做点优化
> > 
> > 
> > TRT加速可以达到100多，我那个是测了一个500frame的视频[OTB中]。1080ti我没有测试，之前在上面配TRT没成功，现在都用的2080ti我这边。
> 
> 之前看您的bili视频，讲的是要往简洁以及方便落地上靠，感觉看整个代码框架还是有点懵，训练的batchsize=32写死了，模型暂时不支持cpu测试，后续会持续在OCEAN上做优化吗？感谢

cpu测试这种应该改几句代码就好了，batch你可以自己在yaml里面改，不用OA分支的话`models/ocean.py`里面设置的batch不会影响，也可以加几句代码把那个改成动态的，都很简单。这个仓库不会怎么优化了，后面更改主要都会放在这个[新仓库](https://github.com/JudasDie/SOTS)上面，后面新工作做完后会把框架做个整体优化。

**Comment by codylcs** [comment]
> > > > 题外，想了解下，OCEAN的速度测试可以到168FPS？在1080ti设备可以到多少？这个转容易转到libtorch或者tensorrt吗？因为看到用的后续想沿着速度方向做点优化
> > > 
> > > 
> > > TRT加速可以达到100多，我那个是测了一个500frame的视频[OTB中]。1080ti我没有测试，之前在上面配TRT没成功，现在都用的2080ti我这边。
> > 
> > 
> > 之前看您的bili视频，讲的是要往简洁以及方便落地上靠，感觉看整个代码框架还是有点懵，训练的batchsize=32写死了，模型暂时不支持cpu测试，后续会持续在OCEAN上做优化吗？感谢
> 
> cpu测试这种应该改几句代码就好了，batch你可以自己在yaml里面改，不用OA分支的话`models/ocean.py`里面设置的batch不会影响，也可以加几句代码把那个改成动态的，都很简单。这个仓库不会怎么优化了，后面更改主要都会放在这个[新仓库](https://github.com/JudasDie/SOTS)上面，后面新工作做完后会把框架做个整体优化。

关注那个仓库了，OCEAN++的train code什么时候可以release？哈哈

**Comment by JudasDie** [comment]
> > > > > 题外，想了解下，OCEAN的速度测试可以到168FPS？在1080ti设备可以到多少？这个转容易转到libtorch或者tensorrt吗？因为看到用的后续想沿着速度方向做点优化
> > > > 
> > > > 
> > > > TRT加速可以达到100多，我那个是测了一个500frame的视频[OTB中]。1080ti我没有测试，之前在上面配TRT没成功，现在都用的2080ti我这边。
> > > 
> > > 
> > > 之前看您的bili视频，讲的是要往简洁以及方便落地上靠，感觉看整个代码框架还是有点懵，训练的batchsize=32写死了，模型暂时不支持cpu测试，后续会持续在OCEAN上做优化吗？感谢
> > 
> > 
> > cpu测试这种应该改几句代码就好了，batch你可以自己在yaml里面改，不用OA分支的话`models/ocean.py`里面设置的batch不会影响，也可以加几句代码把那个改成动态的，都很简单。这个仓库不会怎么优化了，后面更改主要都会放在这个[新仓库](https://github.com/JudasDie/SOTS)上面，后面新工作做完后会把框架做个整体优化。
> 
> 关注那个仓库了，OCEAN++的train code什么时候可以release？哈哈

可能得等有机会中了之后吧，哈哈。其实那个模型只要有测试就差不多了，训练的话按照分割的搞搞就差不多了。

**Comment by codylcs** [comment]
祝论文早日高中！！！^_*
