### ISSUE TITLE
I can't import deform_conv_cuda on win10

### ISSUE THREAD

**Issue by Wanghui-Huang** [researchmm/TracKit#7]
hi zhipeng,

 Sorry to bother you again, I guess this question will confuse some people like me who have to run your code on Windows, so I'm using English and hope more people can join the discussion.

### problem description 
Due to some  reasons, i have to  run your code(Ocean) on win10(two 2080ti gpus) , when i had prepared the datasets and corresponding env.

After run the code ,  i encounter the following mistakes:
```
  Traceback (most recent call last):
  File "D:/hwh/code/TracKit/tracking/train_ocean.py", line 21, in <module>
    import models.models as models
  File "D:\hwh\code\TracKit\tracking\..\lib\models\models.py", line 14, in <module>
    from .connect import box_tower, AdjustLayer, AlignHead, Corr_Up, MultiDiCorr, OceanCorr
  File "D:\hwh\code\TracKit\tracking\..\lib\models\connect.py", line 9, in <module>
    from .dcn import DeformConv, DeformConvPack
  File "D:\hwh\code\TracKit\tracking\..\lib\models\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "D:\hwh\code\TracKit\tracking\..\lib\models\dcn\deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
**ImportError: cannot import name 'deform_conv_cuda' from 'models.dcn'** (D:\hwh\code\TracKit\tracking\..\lib\models\dcn\__init__.py)
```

### for help 
i noticed that this problems is due to the file  `deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so`  is only can be import on the os for linux .

so, could you help me to solve this problem? or tell me how to import this moudle on windows?

thanks for reply! (i have to eat something now , this problem caused me to miss lunch ,hah~)

**Comment by JudasDie** [comment]
> hi zhipeng,
> 
> Sorry to bother you again, I guess this question will confuse some people like me who have to run your code on Windows, so I'm using English and hope more people can join the discussion.
> 
> ### problem description
> Due to some reasons, i have to run your code(Ocean) on win10(two 2080ti gpus) , when i had prepared the datasets and corresponding env.
> 
> After run the code , i encounter the following mistakes:
> 
> ```
>   Traceback (most recent call last):
>   File "D:/hwh/code/TracKit/tracking/train_ocean.py", line 21, in <module>
>     import models.models as models
>   File "D:\hwh\code\TracKit\tracking\..\lib\models\models.py", line 14, in <module>
>     from .connect import box_tower, AdjustLayer, AlignHead, Corr_Up, MultiDiCorr, OceanCorr
>   File "D:\hwh\code\TracKit\tracking\..\lib\models\connect.py", line 9, in <module>
>     from .dcn import DeformConv, DeformConvPack
>   File "D:\hwh\code\TracKit\tracking\..\lib\models\dcn\__init__.py", line 1, in <module>
>     from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
>   File "D:\hwh\code\TracKit\tracking\..\lib\models\dcn\deform_conv.py", line 9, in <module>
>     from . import deform_conv_cuda
> **ImportError: cannot import name 'deform_conv_cuda' from 'models.dcn'** (D:\hwh\code\TracKit\tracking\..\lib\models\dcn\__init__.py)
> ```
> 
> ### for help
> i noticed that this problems is due to the file `deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so` is only can be import on the os for linux .
> 
> so, could you help me to solve this problem? or tell me how to import this moudle on windows?
> 
> thanks for reply! (i have to eat something now , this problem caused me to miss lunch ,hah~)

Hi, I haven't tested the model on windows. Have you checked the original `deform_conv` setup in [MMdetection](https://github.com/open-mmlab/mmdetection)?

**Comment by huangwanghuiYY** [comment]
Thank for your reply . 

The problems  it seems that can't be solve on windows ,  I will update the issue If I find a solution.

**Comment by Wanghui-Huang** [comment]
> Due to some reasons, a month later I started running code again, but other error had appear 

Now my environment is as follows: 
- ubantu16 + 2080ti*2 + cuda10.2 

when I run the code again , I encountered the following error :
`ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory`
After I reinstalled CUDA and demoted to 9.0 to solve this problem:
`conda install -y pytorch torchvision cudatoolkit=9.0`

However, I encountered  other error:` cuda driver(10.2)and CUDA versions(9.0) do not match. `
1. 2080ti only support cuda>=10.0, so I don't want to  reinstall cuda to 9.0
2. Could you tell me how to **generate the files like deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so?** I want to recompile and generate the files in my computer may  help me solve this problem.

Thanks for your reply!

**Comment by JudasDie** [comment]
> > Due to some reasons, a month later I started running code again, but other error had appear
> 
> Now my environment is as follows:
> 
> * ubantu16 + 2080ti*2 + cuda10.2
> 
> when I run the code again , I encountered the following error :
> `ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory`
> After I reinstalled CUDA and demoted to 9.0 to solve this problem:
> `conda install -y pytorch torchvision cudatoolkit=9.0`
> 
> However, I encountered other error:`cuda driver(10.2)and CUDA versions(9.0) do not match.`
> 
> 1. 2080ti only support cuda>=10.0, so I don't want to  reinstall cuda to 9.0
> 2. Could you tell me how to **generate the files like deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so?** I want to recompile and generate the files in my computer may  help me solve this problem.
> 
> Thanks for your reply!

Hi, I have run code on 2080Ti with CUDA10.0. There is no need to install pytorch with cuda9 version. Have you set up DECONV with `pip setup.py install`?

**Comment by Wanghui-Huang** [comment]
### Problem had solved 
I  build env again  followed your tutorial carefully :
```
cd $TracKit/lib/tutorial
bash install.sh $conda_path TracKit
cd $TracKit
conda activate TracKit
python setup.py develop
```
Modifed the config files ocean.yaml ,  now I had  solved this problem .  
Some  advices  for  people who encountered   similar problems:
1. Pls run code on  linux  not windows, Unless absolutely necessary
2. Check it whether you execute setup.py correctly

### Supplement
I will give a detailed report of my result in the next few days  before i close the issue.

Finally, I would like to express my special thanks to zhipeng for his careful guidance. 👍

**Comment by JudasDie** [comment]
> ### Problem had solved
> I build env again followed your tutorial carefully :
> 
> ```
> cd $TracKit/lib/tutorial
> bash install.sh $conda_path TracKit
> cd $TracKit
> conda activate TracKit
> python setup.py develop
> ```
> 
> Modifed the config files ocean.yaml , now I had solved this problem .
> Some advices for people who encountered similar problems:
> 
> 1. Pls run code on  linux  not windows, Unless absolutely necessary
> 2. Check it whether you execute setup.py correctly
> 
> ### Supplement
> I will give a detailed report of my result in the next few days before i close the issue.
> 
> Finally, I would like to express my special thanks to zhipeng for his careful guidance. 👍

You are so welcome. Glad to help you.
