### ISSUE TITLE
请教关于ocean+中ARN模块推理速度

### ISSUE THREAD

**Issue by Wanghui-Huang** [researchmm/TracKit#70]
鹏哥，您好！
    您论文中ocean+中ARN模块对推理速度影响具体如何？我实际测试时，影响比想象中大，想请教下您自己测试时速度影响如何。
   感谢鹏哥百忙中回复。

**Comment by JudasDie** [comment]
> 鹏哥，您好！
> 您论文中ocean+中ARN模块对推理速度影响具体如何？我实际测试时，影响比想象中大，想请教下您自己测试时速度影响如何。
> 感谢鹏哥百忙中回复。

你好哈，ARN只有几个矩阵相乘应该不会影响很大，影响大的应该是逐步上采样分割那块。

**Comment by Wanghui-Huang** [comment]
谢谢您，上次忙完忘了回复抱歉。是我自己的测试环境出了点问题，导致耗时多了点。
