### ISSUE TITLE
How exactly did you set hyperparameters?

### ISSUE THREAD

**Issue by kumatheworld** [researchmm/TracKit#74]
Since different hyperparameter values are used in different config files, I'd like to know how exactly you chose those values.

For example, on which dataset did you tune the hyperparameters in experiments/test/OTB/Ocean.yaml?

**Comment by penghouwen** [comment]
@JudasDie  would you help to address this issue?

**Comment by JudasDie** [comment]
> Since different hyperparameter values are used in different config files, I'd like to know how exactly you chose those values.
> 
> For example, on which dataset did you tune the hyperparameters in experiments/test/OTB/Ocean.yaml?

You could use the `tune tool` in our repo or `grid search tool` in [pysot](https://github.com/STVIR/pysot).

**Comment by kumatheworld** [comment]
Thanks, but I'm still wondering how you did that. Which dataset did you use for [this](https://github.com/researchmm/TracKit/blob/master/experiments/test/OTB/Ocean.yaml)?
