### ISSUE TITLE
About testing OTB2015

### ISSUE THREAD

**Issue by leonardozxcasdqwe** [researchmm/TracKit#79]
Traceback (most recent call last):
  File "tracking/test_ocean.py", line 390, in <module>
    main()
  File "tracking/test_ocean.py", line 232, in main
    dataset = load_dataset(args.dataset)
  File "lib/utils/utils.py", line 408, in load_dataset
    path_name = info[v]['name']
KeyError: 'name'

There was an error in testing OTB2015,would you help to solve the problem?

**Comment by JudasDie** [comment]
> Traceback (most recent call last):
> File "tracking/test_ocean.py", line 390, in
> main()
> File "tracking/test_ocean.py", line 232, in main
> dataset = load_dataset(args.dataset)
> File "lib/utils/utils.py", line 408, in load_dataset
> path_name = info[v]['name']
> KeyError: 'name'
> 
> There was an error in testing OTB2015,would you help to solve the problem?

Hi, could you pls check `OTB2015.json` to see whether `name` in dict keys?

**Comment by leonardozxcasdqwe** [comment]
> > {
> > "Basketball":{
> > "video_dir": "Basketball",
> > "init_rect": [198, 214, 34, 81],
> > "img_names": [
> > "Basketball/img/0001.jpg",
> > ... ,
> > "Basketball/img/0725.jpg"],
> > "gt_rect": [
> > [198, 214, 34, 81],
> > ...,
> > [323, 198, 34, 81]],
> > "attr": [
> > "Illumination Variation",
> > "Out-of-Plane Rotation",
> > "Occlusion",
> > "Deformation",
> > "Background Clutters"]}
> > I don't find name in dict keys,dict keys are 'video_dir', 'init_rect' and so on.Is this json file not right?
> 
> It seems that the `OTB2015.json` is not downloaded from our drive (maybe pysot?). Pls re-download it following the tutorials.
> ![image](https://user-images.githubusercontent.com/24988988/120455343-43e63280-c3c7-11eb-93a8-709843da4937.png)

Thanks! Problem has resolved.

**Comment by leonardozxcasdqwe** [comment]
Traceback (most recent call last):
  File "lib/eval_toolkit/bin/eval.py", line 36, in <module>
    dataset = OTBDataset(args.dataset, root)
  File "eval_toolkit/pysot/datasets/otb.py", line 96, in __init__
    meta_data[video]['video_dir'],
KeyError: 'video_dir'

The problem in the test part is solved, but there seems to be some problems in the eval part. You use the pysot library to perform eval, but the json file you use is not consistent with the json file used by pysot, and reading problems occur.

**Comment by JudasDie** [comment]
> Traceback (most recent call last):
> File "lib/eval_toolkit/bin/eval.py", line 36, in
> dataset = OTBDataset(args.dataset, root)
> File "eval_toolkit/pysot/datasets/otb.py", line 96, in **init**
> meta_data[video]['video_dir'],
> KeyError: 'video_dir'
> 
> The problem in the test part is solved, but there seems to be some problems in the eval part. You use the pysot library to perform eval, but the json file you use is not consistent with the json file used by pysot, and reading problems occur.

Sorry, I don't use pysot to evaluate my tracker. Pls consider our simple code (see `lib/core/eval_otb.py`).

**Comment by leonardozxcasdqwe** [comment]
> > Traceback (most recent call last):
> > File "lib/eval_toolkit/bin/eval.py", line 36, in
> > dataset = OTBDataset(args.dataset, root)
> > File "eval_toolkit/pysot/datasets/otb.py", line 96, in **init**
> > meta_data[video]['video_dir'],
> > KeyError: 'video_dir'
> > The problem in the test part is solved, but there seems to be some problems in the eval part. You use the pysot library to perform eval, but the json file you use is not consistent with the json file used by pysot, and reading problems occur.
> 
> Sorry, I don't use pysot to evaluate my tracker. Pls consider our simple code (see `lib/core/eval_otb.py`).

Thank you for your reply, your work is very helpful to me

**Comment by JudasDie** [comment]
> > > Traceback (most recent call last):
> > > File "lib/eval_toolkit/bin/eval.py", line 36, in
> > > dataset = OTBDataset(args.dataset, root)
> > > File "eval_toolkit/pysot/datasets/otb.py", line 96, in **init**
> > > meta_data[video]['video_dir'],
> > > KeyError: 'video_dir'
> > > The problem in the test part is solved, but there seems to be some problems in the eval part. You use the pysot library to perform eval, but the json file you use is not consistent with the json file used by pysot, and reading problems occur.
> > 
> > 
> > Sorry, I don't use pysot to evaluate my tracker. Pls consider our simple code (see `lib/core/eval_otb.py`).
> 
> Thank you for your reply, your work is very helpful to me

You are welcome.
