### ISSUE TITLE
test online model

### ISSUE THREAD

**Issue by zzzmm1** [researchmm/TracKit#8]
Thanks for your great work!
I want to know how to test with online model like OceanV18on.pth?
I have tried python tracking/test_ocean.py --arch Ocean --resume snapshot/OceanV18on.pth --dataset VOT2018 --online True but didn't work.

**Comment by JudasDie** [comment]
> Thanks for your great work!
> I want to know how to test with online model like OceanV18on.pth?
> I have tried python tracking/test_ocean.py --arch Ocean --resume snapshot/OceanV18on.pth --dataset VOT2018 --online True but didn't work.

Hi, could you provide a detailed screenshot?

**Comment by zzzmm1** [comment]
===> init Siamese <====
load pretrained model from snapshot/OceanV18on.pth
remove prefix 'module.'
remove prefix 'feature_extractor.'
missing keys:[]
unused checkpoint keys:['classifier.filter_optimizer.log_step_length', 'classifier.feature_extractor.0.weight', 'classifier.filter_initializer.filter_conv.weight', 'classifier.filter_optimizer.label_map_predictor.weight', 'classifier.filter_initializer.filter_conv.bias', 'classifier.filter_optimizer.filter_reg', 'classifier.filter_optimizer.spatial_weight_predictor.weight', 'classifier.filter_optimizer.target_mask_predictor.0.weight']
====> warm up <====
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 50.45it/s]

and then finished without test results

**Comment by JudasDie** [comment]
> ===> init Siamese <====
> load pretrained model from snapshot/OceanV18on.pth
> remove prefix 'module.'
> remove prefix 'feature_extractor.'
> missing keys:[]
> unused checkpoint keys:['classifier.filter_optimizer.log_step_length', 'classifier.feature_extractor.0.weight', 'classifier.filter_initializer.filter_conv.weight', 'classifier.filter_optimizer.label_map_predictor.weight', 'classifier.filter_initializer.filter_conv.bias', 'classifier.filter_optimizer.filter_reg', 'classifier.filter_optimizer.spatial_weight_predictor.weight', 'classifier.filter_optimizer.target_mask_predictor.0.weight']
> ====> warm up <====
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 50.45it/s]
> 
> and then finished without test results

Hi, the message has been well-received. I would give you feedback asap :smile:.

**Comment by JudasDie** [comment]
> ===> init Siamese <====
> load pretrained model from snapshot/OceanV18on.pth
> remove prefix 'module.'
> remove prefix 'feature_extractor.'
> missing keys:[]
> unused checkpoint keys:['classifier.filter_optimizer.log_step_length', 'classifier.feature_extractor.0.weight', 'classifier.filter_initializer.filter_conv.weight', 'classifier.filter_optimizer.label_map_predictor.weight', 'classifier.filter_initializer.filter_conv.bias', 'classifier.filter_optimizer.filter_reg', 'classifier.filter_optimizer.spatial_weight_predictor.weight', 'classifier.filter_optimizer.target_mask_predictor.0.weight']
> ====> warm up <====
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 50.45it/s]
> 
> and then finished without test results

Hi, I think I have found the issue. Before running online, please check your results directory. If you run offline model before, it will generate a directory, namely `result/VOT2018/Ocean`. Please remove this directory.

**Comment by zzzmm1** [comment]
Ok, thanks for your help !

**Comment by zzzmm1** [comment]
Hi, Zhipeng.
I met another problem "RuntimeError: Error building extension '_prroi_pooling'".
Is there any pre requirements？

**Comment by JudasDie** [comment]
> Hi, Zhipeng.
> I met another problem "RuntimeError: Error building extension '_prroi_pooling'".
> Is there any pre requirements？

Yes, the code will automatically compile precise ROI pooling. If you fail to compile it, please check the python environment and CUDA.

**Comment by zzzmm1** [comment]
> > Hi, Zhipeng.
> > I met another problem "RuntimeError: Error building extension '_prroi_pooling'".
> > Is there any pre requirements？
> 
> Yes, the code will automatically compile precise ROI pooling. If you fail to compile it, please check the python environment and CUDA.

My environment was built as the install.sh, pytorch 1.1.0 with cuda 10.0, but still failed.
And I want to know which part in the online model will use precise ROI pooling?
Could I pre build  precise ROI pooling first and then test online , will it makes any difference?

**Comment by JudasDie** [comment]
> > > Hi, Zhipeng.
> > > I met another problem "RuntimeError: Error building extension '_prroi_pooling'".
> > > Is there any pre requirements？
> > 
> > 
> > Yes, the code will automatically compile precise ROI pooling. If you fail to compile it, please check the python environment and CUDA.
> 
> My environment was built as the install.sh, pytorch 1.1.0 with cuda 10.0, but still failed.
> And I want to know which part in the online model will use precise ROI pooling?
> Could I pre build precise ROI pooling first and then test online , will it makes any difference?

The online model use ROI pooling to extract target features, please read code in `lib/models/online` or refer to [this](https://arxiv.org/pdf/1904.07220.pdf). As for the compiling, I recommend you to the [ROI pooling repo](https://github.com/vacancy/PreciseRoIPooling) to find more information on compiling errors.

**Comment by zzzmm1** [comment]
I found the problem  is caused by the downloading  zip file in the lib/models/online/external/PreciseRoIPooling  instead of using git clone PreciseRoIPooling.  It breaks the symbolic links.

**Comment by n1-k0** [comment]
@zzzmm1 Hi! I wonder how to solve this problem. I use git clone PreciseRoIPooling and put it into the lib/models/online/external/PreciseRoIPooling
but still have this error
