### ISSUE TITLE
OceanPlus removed

### ISSUE THREAD

**Issue by raizazel** [researchmm/TracKit#84]
Hi,

I was using OceanPlus and just saw that the tutorial for OceanPlus has been dropped from the README.md is there an issue with OceanPlus?

Also I've experienced some issues with Ocean without the TensorRT implementation, the bounding box tends to get bigger and drift. Same escenario with TensorRT it tracks well, but without it loses the object really fast.

I'm using Cuda 10.2, so that may be the issue.

**Comment by JudasDie** [comment]
> Hi,
> 
> I was using OceanPlus and just saw that the tutorial for OceanPlus has been dropped from the README.md is there an issue with OceanPlus?
> 
> Also I've experienced some issues with Ocean without the TensorRT implementation, the bounding box tends to get bigger and drift. Same escenario with TensorRT it tracks well, but without it loses the object really fast.
> 
> I'm using Cuda 10.2, so that may be the issue.

Hi. OceanPlus has not been accepted yet. Please refer to code in this [repo](https://github.com/JudasDie/SOTS). 
Have you successfully load the checkpoint when you run the tracker on a new video? And could you paste the log for testing the tracker?
