### ISSUE TITLE
Training data on Google Drive down

### ISSUE THREAD

**Issue by theodu** [researchmm/TracKit#87]
Hi ! 
The link of the training data on Google Drive (https://drive.google.com/drive/folders/1ehjVhg6ewdWSWt709zd1TkjWF7UJlQlq?usp=sharing) does not work anymore.
Unfortunately, I can't download from Baidu. 
Could you please fix this ?

Thank you very much in advance !

**Comment by penghouwen** [comment]
pls refer to our most recent work https://github.com/researchmm/Stark and https://github.com/researchmm/LightTrack

**Comment by theodu** [comment]
Thank you very much !
