### ISSUE TITLE
eccv2020

### ISSUE THREAD

**Issue by laisimiao** [researchmm/TracKit#9]
I can not see your paper in ECCV2020 accepted paper list?

**Comment by JudasDie** [comment]
> I can not see your paper in ECCV2020 accepte

![image](https://user-images.githubusercontent.com/24988988/86806937-38ab4b00-c02e-11ea-93bd-2ac8f6f121e8.png)

Hi, you may be confused by the "150 entries" in ECCV website. And we change our title to a tidy one. It will be updated after camera-ready.

**Comment by laisimiao** [comment]
Oh, that's why! BTW, what's the "camera-ready"?

**Comment by JudasDie** [comment]
> Oh, that's why! BTW, what's the "camera-ready"?

The authors of the accepted papers will submit their **final version** to the ECCV before 7.17.
